import"./Bg9kRutz.js";import"./69_IOA4Y.js";import{n}from"./lTSu4Se7.js";import{a as i,t as o}from"./i5qHrSzT.js";var t=o(`<h1 id="the-cleric"><a aria-hidden="true" tabindex="-1" href="#the-cleric"><span class="icon icon-link"></span></a>The Cleric</h1> <p>The lands of Dungeon World are a gods-forsaken mess. They’re lousy with the
walking dead, beasts of all sorts, and the vast unnatural spaces between safe
and temple-blessed civilizations. It is a godless world out there. That’s why
it needs you.</p> <p>Bringing the glory of your god to the heathens isn’t just in your nature—it’s
your calling. It falls to you to proselytize with sword and mace and spell. To
cleave deep into the witless heart of the wilds and plant the seed of divinity
there. Some say that it is best to keep god close to your heart. You know
that’s rubbish. God lives at the edge of a blade.</p> <p>Show the world who is lord.</p> <h2 id="names"><a aria-hidden="true" tabindex="-1" href="#names"><span class="icon icon-link"></span></a>Names</h2> <p><em>Dwarf</em>: Durga, Aelfar, Gerda, Rurgosh, Bjorn, Drummond, Helga, Siggrun, Freya</p> <p><em>Human</em>: Wesley, Brinton, Jon, Sara, Hawthorn, Elise, Clarke, Lenore, Piotr,
Dahlia, Carmine</p> <h2 id="look"><a aria-hidden="true" tabindex="-1" href="#look"><span class="icon icon-link"></span></a>Look</h2> <p>Choose one for each:</p> <p>Kind Eyes, Sharp Eyes, or Sad Eyes</p> <p>Tonsure, Strange Hair, or Bald</p> <p>Flowing Robes, Habit, or Common Garb</p> <p>Thin Body, Knobby Body, or Flabby Body</p> <h2 id="stats"><a aria-hidden="true" tabindex="-1" href="#stats"><span class="icon icon-link"></span></a>Stats</h2> <p>Your maximum HP is 8+Constitution.</p> <p>Your base damage is d6.</p> <h2 id="starting-moves"><a aria-hidden="true" tabindex="-1" href="#starting-moves"><span class="icon icon-link"></span></a>Starting Moves</h2> <p>Choose a race and gain the corresponding move:</p> <h3 id="dwarf"><a aria-hidden="true" tabindex="-1" href="#dwarf"><span class="icon icon-link"></span></a>Dwarf</h3> <p>You are one with stone. When you commune you are also granted a special
version of Words of the Unspeaking as a rote which only works on stone.</p> <h3 id="human"><a aria-hidden="true" tabindex="-1" href="#human"><span class="icon icon-link"></span></a>Human</h3> <p>Your faith is diverse. Choose one wizard spell. You can cast and be granted
that spell as if it was a cleric spell.</p> <p>You start with these moves:</p> <h3 id="deity"><a aria-hidden="true" tabindex="-1" href="#deity"><span class="icon icon-link"></span></a>Deity</h3> <p>You serve and worship some deity or power which grants you spells. Give your
god a name (maybe Helferth, Sucellus, Zorica or Krugon the Bleak) and choose
your deity’s domain:</p> <ul><li>Healing and Restoration</li> <li>Bloody Conquest</li> <li>Civilization</li> <li>Knowledge and Hidden Things</li> <li>The Downtrodden and Forgotten</li> <li>What Lies Beneath</li></ul> <p>Choose one precept of your religion:</p> <ul><li>Your religion preaches the sanctity of suffering, add Petition: Suffering</li> <li>Your religion is cultish and insular, add Petition: Gaining Secrets</li> <li>Your religion has important sacrificial rites, add Petition: Offering</li> <li>Your religion believes in trial by combat, add Petition: Personal Victory</li></ul> <h3 id="divine-guidance"><a aria-hidden="true" tabindex="-1" href="#divine-guidance"><span class="icon icon-link"></span></a>Divine Guidance</h3> <p>When you <strong>petition your deity according to the precept of your religion</strong>,
you are granted some useful knowledge or boon related to your deity’s domain.
The GM will tell you what.</p> <h3 id="turn-undead"><a aria-hidden="true" tabindex="-1" href="#turn-undead"><span class="icon icon-link"></span></a>Turn Undead</h3> <p>When you <strong>hold your holy symbol aloft and call on your deity for
protection</strong>, roll+Wis. ✴On a 7+, so long as you continue to pray and brandish
your holy symbol, no undead may come within reach of you. ✴On a 10+, you also
momentarily daze intelligent undead and cause mindless undead to flee.
Aggression breaks the effects and they are able to act as normal. Intelligent
undead may still find ways to harry you from afar. They’re clever like that.</p> <h3 id="commune"><a aria-hidden="true" tabindex="-1" href="#commune"><span class="icon icon-link"></span></a>Commune</h3> <p>When you <strong>spend uninterrupted time (an hour or so) in quiet communion with
your deity</strong>, you:</p> <ul><li>Lose any spells already granted to you.</li> <li>Are granted new spells of your choice whose total levels don’t exceed your own level+1, and none of which is a higher level than your own level.</li> <li>Prepare all of your rotes, which never count against your limit.</li></ul> <h3 id="cast-a-spell"><a aria-hidden="true" tabindex="-1" href="#cast-a-spell"><span class="icon icon-link"></span></a>Cast a Spell</h3> <p>When you <strong>unleash a spell granted to you by your deity</strong>, roll+Wis. ✴On a
10+, the spell is successfully cast and your deity does not revoke the spell,
so you may cast it again. ✴On a 7–9, the spell is cast, but choose one:</p> <ul><li>You draw unwelcome attention or put yourself in a spot. The GM will tell you how.</li> <li>Your casting distances you from your deity—take -1 ongoing to cast a spell until the next time you commune.</li> <li>After you cast it, the spell is revoked by your deity. You cannot cast the spell again until you commune and have it granted to you.</li></ul> <p>Note that maintaining spells with ongoing effects will sometimes cause a
penalty to your roll to cast a spell.</p> <h2 id="alignment"><a aria-hidden="true" tabindex="-1" href="#alignment"><span class="icon icon-link"></span></a>Alignment</h2> <p>Choose an alignment:</p> <h3 id="good"><a aria-hidden="true" tabindex="-1" href="#good"><span class="icon icon-link"></span></a>Good</h3> <p>Endanger yourself to heal another.</p> <h3 id="lawful"><a aria-hidden="true" tabindex="-1" href="#lawful"><span class="icon icon-link"></span></a>Lawful</h3> <p>Endanger yourself following the precepts of your church or god.</p> <h3 id="evil"><a aria-hidden="true" tabindex="-1" href="#evil"><span class="icon icon-link"></span></a>Evil</h3> <p>Harm another to prove the superiority of your church or god.</p> <h2 id="gear"><a aria-hidden="true" tabindex="-1" href="#gear"><span class="icon icon-link"></span></a>Gear</h2> <p>Your load is 10+Str. You carry dungeon rations (5 uses, 1 weight) and some
symbol of the divine, describe it (0 weight). Choose your defenses:</p> <ul><li>Chainmail (1 armor, 1 weight)</li> <li>Shield (+1 armor, 2 weight)</li></ul> <p>Choose your armament:</p> <ul><li>Warhammer (close, 1 weight)</li> <li>Mace (close, 1 weight)</li> <li>Staff (close, two-handed, 1 weight) and bandages (0 weight)</li></ul> <p>Choose one:</p> <ul><li>Adventuring gear (1 weight) and dungeon rations (5 uses, 1 weight)</li> <li>Healing potion (0 weight)</li></ul> <h2 id="bonds"><a aria-hidden="true" tabindex="-1" href="#bonds"><span class="icon icon-link"></span></a>Bonds</h2> <p>Fill in the name of one of your companions in at least one:</p> <p>_______________ has insulted my deity; I do not trust them.</p> <p>_______________ is a good and faithful person; I trust them
implicitly.</p> <p>_______________ is in constant danger, I will keep them safe.</p> <p>I am working on converting _______________ to my faith.</p> <h2 id="advanced-moves"><a aria-hidden="true" tabindex="-1" href="#advanced-moves"><span class="icon icon-link"></span></a>Advanced Moves</h2> <p>When you gain a level from 2–5, choose from these moves.</p> <h3 id="chosen-one"><a aria-hidden="true" tabindex="-1" href="#chosen-one"><span class="icon icon-link"></span></a>Chosen One</h3> <p>Choose one spell. You are granted that spell as if it was one level lower.</p> <h3 id="invigorate"><a aria-hidden="true" tabindex="-1" href="#invigorate"><span class="icon icon-link"></span></a>Invigorate</h3> <p>When you <strong>heal someone</strong> they take +2 forward to their damage.</p> <h3 id="the-scales-of-life-and-death"><a aria-hidden="true" tabindex="-1" href="#the-scales-of-life-and-death"><span class="icon icon-link"></span></a>The Scales of Life and Death</h3> <p>When <strong>someone takes their last breath in your presence</strong>, they take +1 to the
roll.</p> <h3 id="serenity"><a aria-hidden="true" tabindex="-1" href="#serenity"><span class="icon icon-link"></span></a>Serenity</h3> <p>When you cast a spell you ignore the first -1 penalty from ongoing spells.</p> <h3 id="first-aid"><a aria-hidden="true" tabindex="-1" href="#first-aid"><span class="icon icon-link"></span></a>First Aid</h3> <p>Cure Light Wounds is a rote for you, and therefore doesn’t count against your
limit of granted spells.</p> <h3 id="divine-intervention"><a aria-hidden="true" tabindex="-1" href="#divine-intervention"><span class="icon icon-link"></span></a>Divine Intervention</h3> <p>When you commune you get 1 hold and lose any hold you already had. Spend that
hold when you or an ally takes damage to call on your deity, they intervene
with an appropriate manifestation (a sudden gust of wind, a lucky slip, a
burst of light) and negate the damage.</p> <h3 id="penitent"><a aria-hidden="true" tabindex="-1" href="#penitent"><span class="icon icon-link"></span></a>Penitent</h3> <p>When you <strong>take damage and embrace the pain</strong>, you may take +1d4 damage
(ignoring armor). If you do, take +1 forward to cast a spell.</p> <h3 id="empower"><a aria-hidden="true" tabindex="-1" href="#empower"><span class="icon icon-link"></span></a>Empower</h3> <p>When you cast a spell, on a 10+ you have the option of choosing from the 7–9
list. If you do, you may choose one of these effects as well:</p> <ul><li>The spell’s effects are doubled</li> <li>The spell’s targets are doubled</li></ul> <h3 id="orison-for-guidance"><a aria-hidden="true" tabindex="-1" href="#orison-for-guidance"><span class="icon icon-link"></span></a>Orison for Guidance</h3> <p>When you <strong>sacrifice something of value to your deity and pray for guidance</strong>,
your deity tells you what it would have you do. If you do it, mark experience.</p> <h3 id="divine-protection"><a aria-hidden="true" tabindex="-1" href="#divine-protection"><span class="icon icon-link"></span></a>Divine Protection</h3> <p>When you wear no armor or shield you get 2 armor.</p> <h3 id="devoted-healer"><a aria-hidden="true" tabindex="-1" href="#devoted-healer"><span class="icon icon-link"></span></a>Devoted Healer</h3> <p>When you heal someone else of damage, add your level to the amount of damage
healed.</p> <p>When you gain a level from 6–10, choose from these moves or the level 2–5
moves.</p> <h3 id="anointed"><a aria-hidden="true" tabindex="-1" href="#anointed"><span class="icon icon-link"></span></a>Anointed</h3> <p>Requires: Chosen One</p> <p>Choose one spell in addition to the one you picked for chosen one. You are
granted that spell as if it was one level lower.</p> <h3 id="apotheosis"><a aria-hidden="true" tabindex="-1" href="#apotheosis"><span class="icon icon-link"></span></a>Apotheosis</h3> <p>The first time you <strong>spend time in prayer as appropriate to your god</strong> after
taking this move, choose a feature associated with your deity (rending claws,
wings of sapphire feathers, an all-seeing third eye, etc.). When you emerge
from prayer, you permanently gain that physical feature.</p> <h3 id="reaper"><a aria-hidden="true" tabindex="-1" href="#reaper"><span class="icon icon-link"></span></a>Reaper</h3> <p>When you <strong>take time after a conflict to dedicate your victory to your deity
and deal with the dead</strong>, take +1 forward.</p> <h3 id="providence"><a aria-hidden="true" tabindex="-1" href="#providence"><span class="icon icon-link"></span></a>Providence</h3> <p>Replaces: Serenity</p> <p>You ignore the -1 penalty from two spells you maintain.</p> <h3 id="greater-first-aid"><a aria-hidden="true" tabindex="-1" href="#greater-first-aid"><span class="icon icon-link"></span></a>Greater First Aid</h3> <p>Requires: First Aid</p> <p>Cure Moderate Wounds is a rote for you, and therefore doesn’t count against
your limit of granted spells.</p> <h3 id="divine-invincibility"><a aria-hidden="true" tabindex="-1" href="#divine-invincibility"><span class="icon icon-link"></span></a>Divine Invincibility</h3> <p>Replaces: Divine Intervention</p> <p>When you commune you gain 2 hold and lose any hold you already had. Spend that
hold when you or an ally takes damage to call on your deity, who intervenes
with an appropriate manifestation (a sudden gust of wind, a lucky slip, a
burst of light) and negates the damage.</p> <h3 id="martyr"><a aria-hidden="true" tabindex="-1" href="#martyr"><span class="icon icon-link"></span></a>Martyr</h3> <p>Replaces: Penitent</p> <p>When you <strong>take damage and embrace the pain</strong>, you may take +1d4 damage
(ignoring armor). If you do, take +1 forward to cast a spell and add your
level to any damage done or healed by the spell.</p> <h3 id="divine-armor"><a aria-hidden="true" tabindex="-1" href="#divine-armor"><span class="icon icon-link"></span></a>Divine Armor</h3> <p>Replaces: Divine Protection</p> <p>When you wear no armor or shield you get 3 armor.</p> <h3 id="greater-empower"><a aria-hidden="true" tabindex="-1" href="#greater-empower"><span class="icon icon-link"></span></a>Greater Empower</h3> <p>Replaces: Empower</p> <p>When you cast a spell, on a 10–11 you have the option of choosing from the 7–9
list. If you do, you may choose one of these effects as well. On a 12+ you get
to choose one of these effects for free.</p> <ul><li>The spell’s effects are doubled</li> <li>The spell’s targets are doubled</li></ul> <h3 id="multiclass-dabbler"><a aria-hidden="true" tabindex="-1" href="#multiclass-dabbler"><span class="icon icon-link"></span></a>Multiclass Dabbler</h3> <p>Get one move from another class. Treat your level as one lower for choosing
the move.</p>`,1);function h(e){var a=t();n(226),i(e,a)}export{h as default};
