import"./Bg9kRutz.js";import"./69_IOA4Y.js";import{n as o}from"./CUSK-jMp.js";import{a as n,t as i}from"./DuK_Zf15.js";var t=i(`<h1 id="the-wizard"><a aria-hidden="true" tabindex="-1" href="#the-wizard"><span class="icon icon-link"></span></a>The Wizard</h1> <p>Dungeon World has rules. Not the laws of men or the rule of some petty tyrant.
Bigger, better rules. You drop something—it falls. You can’t make something
out of nothing. The dead stay dead, right?</p> <p>Oh, the things we tell ourselves to feel better about the long, dark nights.</p> <p>You’ve spent so very long poring over those tomes of yours. The experiments
that nearly drove you mad and all the botched summonings that endangered your
very soul. For what? For power. What else is there? Not just the power of King
or Country but the power to boil a man’s blood in his veins. To call on the
thunder of the sky and the churn of the roiling earth. To shrug off the rules
the world holds so dear.</p> <p>Let them cast their sidelong glances. Let them call you “warlock” or
“diabolist.” Who among them can hurl fireballs from their eyes?</p> <p>Yeah. We didn’t think so.</p> <h2 id="names"><a aria-hidden="true" tabindex="-1" href="#names"><span class="icon icon-link"></span></a>Names</h2> <p><em>Elf</em>: Galadiir, Fenfaril, Lilliastre, Phirosalle, Enkirash, Halwyr</p> <p><em>Human</em>: Avon, Morgan, Rath, Ysolde, Ovid, Vitus, Aldara, Xeno, Uri</p> <h2 id="look"><a aria-hidden="true" tabindex="-1" href="#look"><span class="icon icon-link"></span></a>Look</h2> <p>Choose one for each:</p> <p>Haunted Eyes, Sharp Eyes, or Crazy Eyes</p> <p>Styled Hair, Wild Hair, or Pointed Hat</p> <p>Worn Robes, Stylish Robes, or Strange Robes</p> <p>Pudgy Body, Creepy Body, or Thin Body</p> <h2 id="stats"><a aria-hidden="true" tabindex="-1" href="#stats"><span class="icon icon-link"></span></a>Stats</h2> <p>Your maximum HP is 4+Constitution.</p> <p>Your base damage is d4.</p> <h2 id="starting-moves"><a aria-hidden="true" tabindex="-1" href="#starting-moves"><span class="icon icon-link"></span></a>Starting Moves</h2> <p>Choose a race and gain the corresponding move:</p> <h3 id="elf"><a aria-hidden="true" tabindex="-1" href="#elf"><span class="icon icon-link"></span></a>Elf</h3> <p>Magic is as natural as breath to you. Detect Magic is a cantrip for you.</p> <h3 id="human"><a aria-hidden="true" tabindex="-1" href="#human"><span class="icon icon-link"></span></a>Human</h3> <p>Choose one cleric spell. You can cast it as if it was a wizard spell.</p> <p>You start with these moves:</p> <h3 id="spellbook"><a aria-hidden="true" tabindex="-1" href="#spellbook"><span class="icon icon-link"></span></a>Spellbook</h3> <p>You have mastered several spells and inscribed them in your spellbook. You
start out with three first level spells in your spellbook as well as the
cantrips. Whenever you gain a level, you add a new spell of your level or
lower to your spellbook. You spellbook is 1 weight.</p> <h3 id="prepare-spells"><a aria-hidden="true" tabindex="-1" href="#prepare-spells"><span class="icon icon-link"></span></a>Prepare Spells</h3> <p>When you <strong>spend uninterrupted time (an hour or so) in quiet contemplation
of your spellbook</strong>, you:</p> <ul><li>Lose any spells you already have prepared</li> <li>Prepare new spells of your choice from your spellbook whose total levels don’t exceed your own level+1.</li> <li>Prepare your cantrips which never count against your limit.</li></ul> <h3 id="cast-a-spell-int"><a aria-hidden="true" tabindex="-1" href="#cast-a-spell-int"><span class="icon icon-link"></span></a>Cast a Spell (Int)</h3> <p>When you <strong>release a spell you’ve prepared</strong>, roll+Int. ✴On a 10+, the spell
is successfully cast and you do not forget the spell—you may cast it again
later. ✴On a 7-9, the spell is cast, but choose one:</p> <ul><li>You draw unwelcome attention or put yourself in a spot. The GM will tell you how.</li> <li>The spell disturbs the fabric of reality as it is cast—take -1 ongoing to cast a spell until the next time you Prepare Spells.</li> <li>After it is cast, the spell is forgotten. You cannot cast the spell again until you prepare spells.</li></ul> <p>Note that maintaining spells with ongoing effects will sometimes cause a
penalty to your roll to cast a spell.</p> <h3 id="spell-defense"><a aria-hidden="true" tabindex="-1" href="#spell-defense"><span class="icon icon-link"></span></a>Spell Defense</h3> <p>You may end any ongoing spell immediately and use the energy of its
dissipation to deflect an oncoming attack. The spell ends and you subtract its
level from the damage done to you.</p> <h3 id="ritual"><a aria-hidden="true" tabindex="-1" href="#ritual"><span class="icon icon-link"></span></a>Ritual</h3> <p>When you <strong>draw on a place of power to create a magical effect</strong>, tell the GM
what you’re trying to achieve. Ritual effects are always possible, but the GM
will give you one to four of the following conditions:</p> <ul><li>It’s going to take days/weeks/months</li> <li>First you must ____</li> <li>You’ll need help from ____</li> <li>It will require a lot of money</li> <li>The best you can do is a lesser version, unreliable and limited</li> <li>You and your allies will risk danger from ____</li> <li>You’ll have to disenchant ____ to do it</li></ul> <h2 id="alignment"><a aria-hidden="true" tabindex="-1" href="#alignment"><span class="icon icon-link"></span></a>Alignment</h2> <p>Choose an alignment:</p> <h3 id="good"><a aria-hidden="true" tabindex="-1" href="#good"><span class="icon icon-link"></span></a>Good</h3> <p>Use magic to directly aid another.</p> <h3 id="neutral"><a aria-hidden="true" tabindex="-1" href="#neutral"><span class="icon icon-link"></span></a>Neutral</h3> <p>Discover something about a magical mystery.</p> <h3 id="evil"><a aria-hidden="true" tabindex="-1" href="#evil"><span class="icon icon-link"></span></a>Evil</h3> <p>Use magic to cause terror and fear.</p> <h2 id="gear"><a aria-hidden="true" tabindex="-1" href="#gear"><span class="icon icon-link"></span></a>Gear</h2> <p>Your load is 7+Str. You start with your spellbook (1 weight) and dungeon
rations (5 uses, 1 weight). Choose your defenses:</p> <ul><li>Leather armor (1 armor, 1 weight)</li> <li>Bag of books (5 uses, 2 weight) and 3 healing potions</li></ul> <p>Choose your weapon:</p> <ul><li>Dagger (hand, 1 weight)</li> <li>Staff (close, two-handed, 1 weight)</li></ul> <p>Choose one:</p> <ul><li>Healing potion (0 weight)</li> <li>3 antitoxins (0 weight)</li></ul> <h2 id="bonds"><a aria-hidden="true" tabindex="-1" href="#bonds"><span class="icon icon-link"></span></a>Bonds</h2> <p>Fill in the name of one of your companions in at least one:</p> <p>_______________ will play an important role in the events to
come. I have foreseen it!</p> <p>_______________ is keeping an important secret from me.</p> <p>_______________ is woefully misinformed about the world; I will
teach them all that I can.</p> <h2 id="advanced-moves"><a aria-hidden="true" tabindex="-1" href="#advanced-moves"><span class="icon icon-link"></span></a>Advanced Moves</h2> <p>When you gain a level from 2-5, choose from these moves. You also add a new
spell to your spellbook at each level.</p> <h3 id="prodigy"><a aria-hidden="true" tabindex="-1" href="#prodigy"><span class="icon icon-link"></span></a>Prodigy</h3> <p>Choose a spell. You prepare that spell as if it were one level lower.</p> <h3 id="empowered-magic"><a aria-hidden="true" tabindex="-1" href="#empowered-magic"><span class="icon icon-link"></span></a>Empowered Magic</h3> <p>When you cast a spell, on a 10+ you have the option of choosing from the 7-9
list. If you do, you may choose one of these as well:</p> <ul><li>The spell’s effects are maximized</li> <li>The spell’s targets are doubled</li></ul> <h3 id="fount-of-knowledge"><a aria-hidden="true" tabindex="-1" href="#fount-of-knowledge"><span class="icon icon-link"></span></a>Fount of Knowledge</h3> <p>When you <strong>spout lore about something no one else has any clue about</strong>, take
+1.</p> <h3 id="know-it-all"><a aria-hidden="true" tabindex="-1" href="#know-it-all"><span class="icon icon-link"></span></a>Know-It-All</h3> <p>When <strong>another player’s character comes to you for advice and you tell them
what you think is best</strong>, they get +1 forward when following your advice and
you mark experience if they do.</p> <h3 id="expanded-spellbook"><a aria-hidden="true" tabindex="-1" href="#expanded-spellbook"><span class="icon icon-link"></span></a>Expanded Spellbook</h3> <p>Add a new spell from the spell list of any class to your spellbook.</p> <h3 id="enchanter"><a aria-hidden="true" tabindex="-1" href="#enchanter"><span class="icon icon-link"></span></a>Enchanter</h3> <p>When you have time and safety with a magic item you may ask the GM what it
does, the GM will answer you truthfully.</p> <h3 id="logical"><a aria-hidden="true" tabindex="-1" href="#logical"><span class="icon icon-link"></span></a>Logical</h3> <p>When you <strong>use strict deduction to analyze your surroundings</strong>, you can
discern realities with INT instead of WIS.</p> <h3 id="arcane-ward"><a aria-hidden="true" tabindex="-1" href="#arcane-ward"><span class="icon icon-link"></span></a>Arcane Ward</h3> <p>As long as you have at least one prepared spell of first level or higher, you
have +2 armor.</p> <h3 id="counterspell"><a aria-hidden="true" tabindex="-1" href="#counterspell"><span class="icon icon-link"></span></a>Counterspell</h3> <p>When you <strong>attempt to counter an arcane spell that will otherwise affect
you</strong>, stake one of your prepared spells on the defense and roll+Int. ✴On a
10+, the spell is countered and has no effect on you. ✴On a 7-9, the spell is
countered and you forget the spell you staked. Your counterspell protects only
you; if the countered spell has other targets they get its effects.</p> <h3 id="quick-study"><a aria-hidden="true" tabindex="-1" href="#quick-study"><span class="icon icon-link"></span></a>Quick Study</h3> <p>When you <strong>see the effects of an arcane spell</strong>, ask the GM the name of the
spell and its effects. You take +1 when acting on the answers.</p> <p>When you gain a level from 6-10, choose from these moves or the level 2-5
moves.</p> <h3 id="master"><a aria-hidden="true" tabindex="-1" href="#master"><span class="icon icon-link"></span></a>Master</h3> <p>Requires: Prodigy</p> <p>Choose one spell in addition to the one you picked for prodigy. You prepare
that spell as if it were one level lower.</p> <h3 id="greater-empowered-magic"><a aria-hidden="true" tabindex="-1" href="#greater-empowered-magic"><span class="icon icon-link"></span></a>Greater Empowered Magic</h3> <p>Replaces: Empowered Magic</p> <p>When you cast a spell, on a 10-11 you have the option of choosing from the 7-9
list. If you do, you may choose one of these effects as well. On a 12+ you get
to choose one of these effects for free:</p> <ul><li>The spell’s effects are doubled</li> <li>The spell’s targets are doubled</li></ul> <h3 id="enchanters-soul"><a aria-hidden="true" tabindex="-1" href="#enchanters-soul"><span class="icon icon-link"></span></a>Enchanter’s Soul</h3> <p>Requires: Enchanter</p> <p>When you have time and safety with a magic item in a place of power you can
empower that item so that the next time you use it its effects are amplified,
the GM will tell you exactly how.</p> <h3 id="highly-logical"><a aria-hidden="true" tabindex="-1" href="#highly-logical"><span class="icon icon-link"></span></a>Highly Logical</h3> <p>Replaces: Logical</p> <p>When you <strong>use strict deduction to analyze your surroundings</strong>, you can
discern realities with Int instead of Wis. On a 12+ you get to ask the GM any
three questions, not limited by the list.</p> <h3 id="arcane-armor"><a aria-hidden="true" tabindex="-1" href="#arcane-armor"><span class="icon icon-link"></span></a>Arcane Armor</h3> <p>Replaces: Arcane Ward</p> <p>As long as you have at least one prepared spell of first level or higher, you
have +4 armor.</p> <h3 id="protective-counter"><a aria-hidden="true" tabindex="-1" href="#protective-counter"><span class="icon icon-link"></span></a>Protective Counter</h3> <p>Requires: Counterspell</p> <p>When an ally within sight of you is affected by an arcane spell, you can
counter it as if it affected you. If the spell affects multiple allies you
must counter for each ally separately.</p> <h3 id="ethereal-tether"><a aria-hidden="true" tabindex="-1" href="#ethereal-tether"><span class="icon icon-link"></span></a>Ethereal Tether</h3> <p>When you have time with a willing or helpless subject you can craft an
ethereal tether with them. You perceive what they perceive and can discern
realities about someone tethered to you or their surroundings no matter the
distance. Someone willingly tethered to you can communicate with you over the
tether as if you were in the room with them.</p> <h3 id="mystical-puppet-strings"><a aria-hidden="true" tabindex="-1" href="#mystical-puppet-strings"><span class="icon icon-link"></span></a>Mystical Puppet Strings</h3> <p>When you <strong>use magic to control a person’s actions</strong> they have no memory of
what you had them do and bear you no ill will.</p> <h3 id="spell-augmentation"><a aria-hidden="true" tabindex="-1" href="#spell-augmentation"><span class="icon icon-link"></span></a>Spell Augmentation</h3> <p>When you <strong>deal damage to a creature</strong> you can shunt a spell’s energy into
them—end one of your ongoing spells and add the spell’s level to the damage
dealt.</p> <h3 id="self-powered"><a aria-hidden="true" tabindex="-1" href="#self-powered"><span class="icon icon-link"></span></a>Self-Powered</h3> <p>When you have time, arcane materials, and a safe space, you can create your
own place of power. Describe to the GM what kind of power it is and how you’re
binding it to this place, the GM will tell you one kind of creature that will
have an interest in your workings.</p>`,1);function p(e){var a=t();o(218),n(e,a)}export{p as default};
