import"./Bg9kRutz.js";import"./69_IOA4Y.js";import{n as o}from"./C-zC7P9M.js";import{a as n,t as i}from"./DiJJ1AKy.js";var t=i(`<h1 id="the-thief"><a aria-hidden="true" tabindex="-1" href="#the-thief"><span class="icon icon-link"></span></a>The Thief</h1> <p>You’ve heard them, sitting around the campfire. Bragging about this battle or
that. About how their gods are smiling on your merry band. You count your
coins and smile to yourself—this is the thrill above all. You alone know the
secret of Dungeon World—filthy filthy lucre.</p> <p>Sure, they give you lip for all the times you’ve snuck off alone but without
you, who among them wouldn’t have been dissected by a flying guillotine or
poisoned straight to death by some ancient needle trap? So, let them complain.
When you’re done with all this delving you’ll toast their hero’s graves.</p> <p>From your castle. Full of gold. You rogue.</p> <h2 id="names"><a aria-hidden="true" tabindex="-1" href="#names"><span class="icon icon-link"></span></a>Names</h2> <p><em>Halfling</em>: Felix, Rook, Mouse, Sketch, Trixie, Robin, Omar, Brynn, Bug</p> <p><em>Human</em>: Sparrow, Shank, Jack, Marlow, Dodge, Rat, Pox, Humble, Farley</p> <h2 id="look"><a aria-hidden="true" tabindex="-1" href="#look"><span class="icon icon-link"></span></a>Look</h2> <p>Choose one for each:</p> <p>Shifty Eyes or Criminal Eyes</p> <p>Hooded Head, Messy Hair, or Cropped Hair</p> <p>Dark Clothes, Fancy Clothes, or Common Clothes</p> <p>Lithe Body, Knobby Body, or Flabby Body</p> <h2 id="stats"><a aria-hidden="true" tabindex="-1" href="#stats"><span class="icon icon-link"></span></a>Stats</h2> <p>Your maximum HP is 6+Constitution.</p> <p>Your base damage is d8.</p> <h2 id="starting-moves"><a aria-hidden="true" tabindex="-1" href="#starting-moves"><span class="icon icon-link"></span></a>Starting Moves</h2> <p>Choose a race and gain the corresponding move:</p> <h3 id="halfling"><a aria-hidden="true" tabindex="-1" href="#halfling"><span class="icon icon-link"></span></a>Halfling</h3> <p>When you attack with a ranged weapon, deal +2 damage.</p> <h3 id="human"><a aria-hidden="true" tabindex="-1" href="#human"><span class="icon icon-link"></span></a>Human</h3> <p>You are a professional. When you spout lore or discern realities about
criminal activities, take +1.</p> <p>You start with these moves:</p> <h3 id="trap-expert"><a aria-hidden="true" tabindex="-1" href="#trap-expert"><span class="icon icon-link"></span></a>Trap Expert</h3> <p>When you <strong>spend a moment to survey a dangerous area</strong>, roll+DEX. ✴On a 10+,
hold 3. ✴On a 7–9, hold 1. Spend your hold as you walk through the area to ask
these questions:</p> <ul><li>Is there a trap here and if so, what activates it?</li> <li>What does the trap do when activated?</li> <li>What else is hidden here?</li></ul> <h3 id="tricks-of-the-trade"><a aria-hidden="true" tabindex="-1" href="#tricks-of-the-trade"><span class="icon icon-link"></span></a>Tricks of the Trade</h3> <p>When you <strong>pick locks or pockets or disable traps</strong>, roll+DEX. ✴On a 10+, you
do it, no problem. ✴On a 7–9, you still do it, but the GM will offer you two
options between suspicion, danger, or cost.</p> <h3 id="backstab"><a aria-hidden="true" tabindex="-1" href="#backstab"><span class="icon icon-link"></span></a>Backstab</h3> <p>When you <strong>attack a surprised or defenseless enemy with a melee weapon</strong>, you
can choose to deal your damage or roll+DEX. ✴On a 10+ choose two. ✴On a 7–9
choose one.</p> <ul><li>You don’t get into melee with them</li> <li>You deal your damage+1d6</li> <li>You take the initiative, +1 forward to you or an ally acting on it</li> <li>Reduce their armor by 1 until they repair it</li></ul> <h3 id="flexible-morals"><a aria-hidden="true" tabindex="-1" href="#flexible-morals"><span class="icon icon-link"></span></a>Flexible Morals</h3> <p>When someone tries to detect your alignment you can tell them any alignment
you like.</p> <h3 id="poisoner"><a aria-hidden="true" tabindex="-1" href="#poisoner"><span class="icon icon-link"></span></a>Poisoner</h3> <p>You’ve mastered the care and use of a poison. Choose a poison from the list
below; that poison is no longer dangerous for you to use. You also start with
three uses of the poison you choose. Whenever you have time to gather
materials and a safe place to brew you can make three uses of the poison you
choose for free. Note that some poisons are applied, meaning you have to
carefully apply it to the target or something they eat or drink. Touch poisons
just need to touch the target, they can even be used on the blade of a weapon.</p> <ul><li>Oil of Tagit (applied): The target falls into a light sleep</li> <li>Bloodweed (touch): The target deals -1d4 damage ongoing until cured</li> <li>Goldenroot (applied): The target treats the next creature they see as a trusted ally, until proved otherwise</li> <li>Serpent’s Tears (touch): Anyone dealing damage to the target rolls twice and takes the better result.</li></ul> <h2 id="alignment"><a aria-hidden="true" tabindex="-1" href="#alignment"><span class="icon icon-link"></span></a>Alignment</h2> <p>Choose an alignment:</p> <h3 id="chaotic"><a aria-hidden="true" tabindex="-1" href="#chaotic"><span class="icon icon-link"></span></a>Chaotic</h3> <p>Leap into danger without a plan.</p> <h3 id="neutral"><a aria-hidden="true" tabindex="-1" href="#neutral"><span class="icon icon-link"></span></a>Neutral</h3> <p>Avoid detection or infiltrate a location.</p> <h3 id="evil"><a aria-hidden="true" tabindex="-1" href="#evil"><span class="icon icon-link"></span></a>Evil</h3> <p>Shift danger or blame from yourself to someone else.</p> <h2 id="gear"><a aria-hidden="true" tabindex="-1" href="#gear"><span class="icon icon-link"></span></a>Gear</h2> <p>Your load is 9+Str. You start with dungeon rations (5 uses, 1 weight),
leather armor (1 armor, 1 weight), 3 uses of your chosen poison, and 10
coins. Choose your arms:</p> <ul><li>Dagger (hand, 1 weight) and short sword (close, 1 weight)</li> <li>Rapier (close, precise, 1 weight)</li></ul> <p>Choose a ranged weapon:</p> <ul><li>3 throwing daggers (thrown, near, 0 weight)</li> <li>Ragged Bow (near, 2 weight) and bundle of arrows (3 ammo, 1 weight)</li></ul> <p>Choose one:</p> <ul><li>Adventuring gear (1 weight)</li> <li>Healing potion (0 weight)</li></ul> <h2 id="bonds"><a aria-hidden="true" tabindex="-1" href="#bonds"><span class="icon icon-link"></span></a>Bonds</h2> <p>Fill in the name of one of your companions in at least one:</p> <p>I stole something from _______________.</p> <p>_______________ has my back when things go wrong.</p> <p>_______________ knows incriminating details about me.</p> <p>_______________ and I have a con running.</p> <h2 id="advanced-moves"><a aria-hidden="true" tabindex="-1" href="#advanced-moves"><span class="icon icon-link"></span></a>Advanced Moves</h2> <p>When you gain a level from 2–5, choose from these moves.</p> <h3 id="cheap-shot"><a aria-hidden="true" tabindex="-1" href="#cheap-shot"><span class="icon icon-link"></span></a>Cheap Shot</h3> <p>When using a precise or hand weapon, your backstab deals an extra +1d6 damage.</p> <h3 id="cautious"><a aria-hidden="true" tabindex="-1" href="#cautious"><span class="icon icon-link"></span></a>Cautious</h3> <p>When you use trap expert you always get +1 hold, even on a 6-.</p> <h3 id="wealth-and-taste"><a aria-hidden="true" tabindex="-1" href="#wealth-and-taste"><span class="icon icon-link"></span></a>Wealth and Taste</h3> <p>When you <strong>make a show of flashing around your most valuable possession</strong>,
choose someone present. They will do anything they can to obtain your item or
one like it.</p> <h3 id="shoot-first"><a aria-hidden="true" tabindex="-1" href="#shoot-first"><span class="icon icon-link"></span></a>Shoot First</h3> <p>You’re never caught by surprise. When an enemy would get the drop on you, you
get to act first instead.</p> <h3 id="poison-master"><a aria-hidden="true" tabindex="-1" href="#poison-master"><span class="icon icon-link"></span></a>Poison Master</h3> <p>After you’ve used a poison once it’s no longer dangerous for you to use.</p> <h3 id="envenom"><a aria-hidden="true" tabindex="-1" href="#envenom"><span class="icon icon-link"></span></a>Envenom</h3> <p>You can apply even complex poisons with a pinprick. When you apply a poison
that’s not dangerous for you to use to your weapon it’s touch instead of
applied.</p> <h3 id="brewer"><a aria-hidden="true" tabindex="-1" href="#brewer"><span class="icon icon-link"></span></a>Brewer</h3> <p>When you have time to gather materials and a safe place to brew you can create
three doses of any one poison you’ve used before.</p> <h3 id="underdog"><a aria-hidden="true" tabindex="-1" href="#underdog"><span class="icon icon-link"></span></a>Underdog</h3> <p>When you’re outnumbered, you have +1 armor.</p> <h3 id="connections"><a aria-hidden="true" tabindex="-1" href="#connections"><span class="icon icon-link"></span></a>Connections</h3> <p>When you put out word to the criminal underbelly about something you want or
need, roll+CHA. ✴On a 10+, someone has it, just for you. ✴On a 7–9, you’ll
have to settle for something close or it comes with strings attached, your
call.</p> <p>When you gain a level from 6–10, choose from these moves or the level 2–5
moves.</p> <h3 id="dirty-fighter"><a aria-hidden="true" tabindex="-1" href="#dirty-fighter"><span class="icon icon-link"></span></a>Dirty Fighter</h3> <p>Replaces: Cheap Shot</p> <p>When using a precise or hand weapon, your backstab deals an extra +1d8 damage
and all other attacks deal +1d4 damage.</p> <h3 id="extremely-cautious"><a aria-hidden="true" tabindex="-1" href="#extremely-cautious"><span class="icon icon-link"></span></a>Extremely Cautious</h3> <p>Replaces: Cautious</p> <p>When you use trap expert you always get +1 hold, even on a 6-. On a 12+ you
get 3 hold and the next time you come near a trap the GM will immediately tell
you what it does, what triggers it, who set it, and how you can use it to your
advantage.</p> <h3 id="alchemist"><a aria-hidden="true" tabindex="-1" href="#alchemist"><span class="icon icon-link"></span></a>Alchemist</h3> <p>Replaces: Brewer</p> <p>When you have you have time to gather materials and a safe place to brew you
can create three doses of any poison you’ve used before. Alternately you can
describe the effects of a poison you’d like to create. The GM will tell you
that you can create it, but with one or more caveats:</p> <ul><li>It will only work under specific circumstances</li> <li>The best you can manage is a weaker version</li> <li>It’ll take a while to take effect</li> <li>It’ll have obvious side effects</li></ul> <h3 id="serious-underdog"><a aria-hidden="true" tabindex="-1" href="#serious-underdog"><span class="icon icon-link"></span></a>Serious Underdog</h3> <p>Replaces: Underdog</p> <p>You have +1 armor. When you’re outnumbered, you have +2 armor instead.</p> <h3 id="evasion"><a aria-hidden="true" tabindex="-1" href="#evasion"><span class="icon icon-link"></span></a>Evasion</h3> <p>When you defy danger on a 12+, you transcend the danger. You not only do what
you set out to, but the GM will offer you a better outcome, true beauty, or a
moment of grace.</p> <h3 id="strong-arm-true-aim"><a aria-hidden="true" tabindex="-1" href="#strong-arm-true-aim"><span class="icon icon-link"></span></a>Strong Arm, True Aim</h3> <p>You can throw any melee weapon, using it to volley. A thrown melee weapon is
gone; you can never choose to reduce ammo on a 7–9.</p> <h3 id="escape-route"><a aria-hidden="true" tabindex="-1" href="#escape-route"><span class="icon icon-link"></span></a>Escape Route</h3> <p>When you’re in too deep and need a way out, name your escape route and
roll+DEX. ✴On a 10+ you’re gone. ✴On a 7–9 you can stay or go, but if you go
it costs you: leave something behind or take something with you, the GM will
tell you what.</p> <h3 id="disguise"><a aria-hidden="true" tabindex="-1" href="#disguise"><span class="icon icon-link"></span></a>Disguise</h3> <p>When you have time and materials you can create a disguise that will fool
anyone into thinking you’re another creature of about the same size and shape.
Your actions can give you away but your appearance won’t.</p> <h3 id="heist"><a aria-hidden="true" tabindex="-1" href="#heist"><span class="icon icon-link"></span></a>Heist</h3> <p>When you take time to make a plan to steal something, name the thing you want
to steal and ask the GM these questions. When acting on the answers you and
your allies take +1 forward.</p> <ul><li>Who will notice it’s missing?</li> <li>What’s its most powerful defense?</li> <li>Who will come after it?</li> <li>Who else wants it?</li></ul>`,1);function d(e){var a=t();o(202),n(e,a)}export{d as default};
