import"./Bg9kRutz.js";import"./69_IOA4Y.js";import{n}from"./Dtm0V8su.js";import{a as o,t as i}from"./C-s_40rX.js";var t=i(`<h1 id="the-bard"><a aria-hidden="true" tabindex="-1" href="#the-bard"><span class="icon icon-link"></span></a>The Bard</h1> <p>The poems say an adventurer’s life is all open roads and the glory of coin and
combat. The tales told in every farmhand-filled inn have to have some ring of
truth to them, don’t they? The songs to inspire peasantry and royals alike—to
soothe the savage beast or drive men to a frenzy—have to come from somewhere.</p> <p>Enter the bard. You, with your smooth tongue and quick wit. You teller-of-
tales and singer-of-songs. It takes a mere minstrel to retell a thing but a
true bard to live it. Strap on your boots, noble orator. Sharpen that hidden
dagger and take up the call. Someone’s got to be there, fighting shoulder-to-
shoulder with the goons and the thugs and the soon-to-be-heroes. Who better
than you to write the tale of your own heroism?</p> <p>Nobody. Get going.</p> <h2 id="names"><a aria-hidden="true" tabindex="-1" href="#names"><span class="icon icon-link"></span></a>Names</h2> <p><em>Elf</em>: Astrafel, Daelwyn, Feliana, Damarra, Sistranalle, Pendrell, Melliandre,
Dagoliir</p> <p><em>Human</em>: Baldric, Leena, Dunwick, Willem, Edwyn, Florian, Seraphine, Quorra,
Charlotte, Lily, Ramonde, Cassandra</p> <h2 id="look"><a aria-hidden="true" tabindex="-1" href="#look"><span class="icon icon-link"></span></a>Look</h2> <p>Choose one for each:</p> <p>Knowing Eyes, Fiery Eyes, or Joyous Eyes</p> <p>Fancy Hair, Wild Hair, or Stylish Cap</p> <p>Finery, Traveling Clothes, or Poor Clothes</p> <p>Fit Body, Well-fed Body, or Thin Body</p> <h2 id="stats"><a aria-hidden="true" tabindex="-1" href="#stats"><span class="icon icon-link"></span></a>Stats</h2> <p>Your maximum HP is 6+Constitution.</p> <p>Your base damage is d6.</p> <h2 id="starting-moves"><a aria-hidden="true" tabindex="-1" href="#starting-moves"><span class="icon icon-link"></span></a>Starting Moves</h2> <p>Choose a race and gain the corresponding move:</p> <h3 id="elf"><a aria-hidden="true" tabindex="-1" href="#elf"><span class="icon icon-link"></span></a>Elf</h3> <p>When you enter an important location (your call) you can ask the GM for one
fact from the history of that location.</p> <h3 id="human"><a aria-hidden="true" tabindex="-1" href="#human"><span class="icon icon-link"></span></a>Human</h3> <p>When you first enter a civilized settlement someone who respects the custom of
hospitality to minstrels will take you in as their guest.</p> <p>You start with these moves:</p> <h3 id="arcane-art"><a aria-hidden="true" tabindex="-1" href="#arcane-art"><span class="icon icon-link"></span></a>Arcane Art</h3> <p>When you<strong>weave a performance into a basic spell</strong>, choose an ally and an
effect:</p> <ul><li>Heal 1d8 damage</li> <li>+1d4 forward to damage</li> <li>Their mind is shaken clear of one enchantment</li> <li>The next time someone successfully assists the target with aid, they get +2 instead of +1</li></ul> <p>Then roll+Cha. ✴On a 10+, the ally gets the selected effect. ✴On a 7-9, your
spell still works, but you draw unwanted attention or your magic reverberates
to other targets affecting them as well, GM’s choice.</p> <h3 id="bardic-lore"><a aria-hidden="true" tabindex="-1" href="#bardic-lore"><span class="icon icon-link"></span></a>Bardic Lore</h3> <p>Choose an area of expertise:</p> <ul><li>Spells and Magicks</li> <li>The Dead and Undead</li> <li>Grand Histories of the Known World</li> <li>A Bestiary of Creatures Unusual</li> <li>The Planar Spheres</li> <li>Legends of Heroes Past</li> <li>Gods and Their Servants</li></ul> <p>When you <strong>first encounter an important creature, location, or item (your
call) covered by your bardic lore</strong> you can ask the GM any one question about
it; the GM will answer truthfully. The GM may then ask you what tale, song, or
legend you heard that information in.</p> <h3 id="charming-and-open"><a aria-hidden="true" tabindex="-1" href="#charming-and-open"><span class="icon icon-link"></span></a>Charming and Open</h3> <p>When you <strong>speak frankly with someone</strong>, you can ask their player a question
from the list below. They must answer it truthfully, then they may ask you a
question from the list (which you must answer truthfully).</p> <ul><li>Whom do you serve?</li> <li>What do you wish I would do?</li> <li>How can I get you to ______?</li> <li>What are you really feeling right now?</li> <li>What do you most desire?</li></ul> <h3 id="a-port-in-the-storm"><a aria-hidden="true" tabindex="-1" href="#a-port-in-the-storm"><span class="icon icon-link"></span></a>A Port in the Storm</h3> <p>When you <strong>return to a civilized settlement you’ve visited before</strong>, tell the
GM when you were last here. They’ll tell you how it’s changed since then.</p> <h2 id="alignment"><a aria-hidden="true" tabindex="-1" href="#alignment"><span class="icon icon-link"></span></a>Alignment</h2> <p>Choose an alignment:</p> <h3 id="good"><a aria-hidden="true" tabindex="-1" href="#good"><span class="icon icon-link"></span></a>Good</h3> <p>Perform your art to aid someone else.</p> <h3 id="neutral"><a aria-hidden="true" tabindex="-1" href="#neutral"><span class="icon icon-link"></span></a>Neutral</h3> <p>Avoid a conflict or defuse a tense situation.</p> <h3 id="chaotic"><a aria-hidden="true" tabindex="-1" href="#chaotic"><span class="icon icon-link"></span></a>Chaotic</h3> <p>Spur others to significant and unplanned decisive action.</p> <h2 id="gear"><a aria-hidden="true" tabindex="-1" href="#gear"><span class="icon icon-link"></span></a>Gear</h2> <p>Your load is 9+Str. You have dungeon rations (5 uses, 1 weight). Choose one
instrument, all are 0 weight for you:</p> <ul><li>Your father’s mandolin, repaired</li> <li>A fine lute, a gift from a noble</li> <li>The pipes with which you courted your first love</li> <li>A stolen horn</li> <li>A fiddle, never before played</li> <li>A songbook in a forgotten tongue</li></ul> <p>Choose your clothing:</p> <ul><li>Leather armor (1 armor, 1 weight)</li> <li>Ostentatious clothes (0 weight)</li></ul> <p>Choose your armament:</p> <ul><li>Dueling rapier (close, precise, 2 weight)</li> <li>Worn bow (near, 2 weight), bundle of arrows (3 ammo, 1 weight), and short sword (close, 1 weight)</li></ul> <p>Choose one:</p> <ul><li>Adventuring gear (1 weight)</li> <li>Bandages (0 weight)</li> <li>Halfling pipeleaf (0 weight)</li> <li>3 coins</li></ul> <h2 id="bonds"><a aria-hidden="true" tabindex="-1" href="#bonds"><span class="icon icon-link"></span></a>Bonds</h2> <p>Fill in the name of one of your companions in at least one:</p> <p>This is not my first adventure with _______________.</p> <p>I sang stories of _______________ long before I ever met them
in person.</p> <p>_______________ is often the butt of my jokes.</p> <p>I am writing a ballad about the adventures of _______________.</p> <p>_______________ trusted me with a secret.</p> <p>_______________ does not trust me, and for good reason.</p> <h2 id="advanced-moves"><a aria-hidden="true" tabindex="-1" href="#advanced-moves"><span class="icon icon-link"></span></a>Advanced Moves</h2> <p>When you gain a level from 2-5, choose from these moves.</p> <h3 id="healing-song"><a aria-hidden="true" tabindex="-1" href="#healing-song"><span class="icon icon-link"></span></a>Healing Song</h3> <p>When you <strong>heal with arcane art</strong>, you heal +1d8 damage.</p> <h3 id="vicious-cacophony"><a aria-hidden="true" tabindex="-1" href="#vicious-cacophony"><span class="icon icon-link"></span></a>Vicious Cacophony</h3> <p>When you <strong>grant bonus damage with arcane art</strong>, you grant an extra +1d4
damage.</p> <h3 id="it-goes-to-eleven"><a aria-hidden="true" tabindex="-1" href="#it-goes-to-eleven"><span class="icon icon-link"></span></a>It Goes To Eleven</h3> <p>When you <strong>unleash a crazed performance</strong> (a righteous lute solo or mighty
brass blast, maybe) choose a target who can hear you and roll+Cha. ✴On a 10+
the target attacks their nearest ally in range. ✴On a 7–9 they attack their
nearest ally, but you also draw their attention and ire.</p> <h3 id="metal-hurlant"><a aria-hidden="true" tabindex="-1" href="#metal-hurlant"><span class="icon icon-link"></span></a>Metal Hurlant</h3> <p>When you <strong>shout with great force or play a shattering note</strong> choose a target
and roll+Con. ✴On a 10+ the target takes 1d10 damage and is deafened for a few
minutes. ✴On a 7–9 you still damage your target, but it’s out of control: the
GM will choose an additional target nearby.</p> <h3 id="a-little-help-from-my-friends"><a aria-hidden="true" tabindex="-1" href="#a-little-help-from-my-friends"><span class="icon icon-link"></span></a>A Little Help From My Friends</h3> <p>When you <strong>successfully aid someone</strong> you take +1 forward as well.</p> <h3 id="eldritch-tones"><a aria-hidden="true" tabindex="-1" href="#eldritch-tones"><span class="icon icon-link"></span></a>Eldritch Tones</h3> <p>Your arcane art is strong, allowing you to choose two effects instead of one.</p> <h3 id="duelists-parry"><a aria-hidden="true" tabindex="-1" href="#duelists-parry"><span class="icon icon-link"></span></a>Duelist’s Parry</h3> <p>When you hack and slash, you take +1 armor forward.</p> <h3 id="bamboozle"><a aria-hidden="true" tabindex="-1" href="#bamboozle"><span class="icon icon-link"></span></a>Bamboozle</h3> <p>When you <strong>parley with someone</strong>, on a 7+ you also take +1 forward with them.</p> <h3 id="multiclass-dabbler"><a aria-hidden="true" tabindex="-1" href="#multiclass-dabbler"><span class="icon icon-link"></span></a>Multiclass Dabbler</h3> <p>Get one move from another class. Treat your level as one lower for choosing
the move.</p> <h3 id="multiclass-initiate"><a aria-hidden="true" tabindex="-1" href="#multiclass-initiate"><span class="icon icon-link"></span></a>Multiclass Initiate</h3> <p>Get one move from another class. Treat your level as one lower for choosing
the move.</p> <p>When you gain a level from 6-10, choose from these moves or the level 2-5
moves.</p> <h3 id="healing-chorus"><a aria-hidden="true" tabindex="-1" href="#healing-chorus"><span class="icon icon-link"></span></a>Healing Chorus</h3> <p>Replaces: Healing Song</p> <p>When you <strong>heal with arcane art</strong>, you heal +2d8 damage.</p> <h3 id="vicious-blast"><a aria-hidden="true" tabindex="-1" href="#vicious-blast"><span class="icon icon-link"></span></a>Vicious Blast</h3> <p>Replaces: Vicious Cacophony</p> <p>When you <strong>grant bonus damage with arcane art</strong>, you grant an extra +2d4
damage.</p> <h3 id="unforgettable-face"><a aria-hidden="true" tabindex="-1" href="#unforgettable-face"><span class="icon icon-link"></span></a>Unforgettable Face</h3> <p>When you <strong>meet someone you’ve met before</strong> (your call) after some time
apart you take +1 forward against them.</p> <h3 id="reputation"><a aria-hidden="true" tabindex="-1" href="#reputation"><span class="icon icon-link"></span></a>Reputation</h3> <p>When you <strong>first meet someone who’s heard songs about you</strong>, roll+Cha. ✴On a
10+, tell the GM two things they’ve heard about you. ✴On a 7-9, tell the GM
one thing they’ve heard, and the GM tells you one thing.</p> <h3 id="eldritch-chord"><a aria-hidden="true" tabindex="-1" href="#eldritch-chord"><span class="icon icon-link"></span></a>Eldritch Chord</h3> <p>Replaces: Eldritch Tones</p> <p>When you use arcane art, you choose two effects. You also get to choose one of
those effects to double.</p> <h3 id="an-ear-for-magic"><a aria-hidden="true" tabindex="-1" href="#an-ear-for-magic"><span class="icon icon-link"></span></a>An Ear For Magic</h3> <p>When you <strong>hear an enemy cast a spell</strong> the GM will tell you the name of the
spell and its effects. Take +1 forward when acting on the answers.</p> <h3 id="devious"><a aria-hidden="true" tabindex="-1" href="#devious"><span class="icon icon-link"></span></a>Devious</h3> <p>When you use charming and open you may also ask “How are you vulnerable to
me?” Your subject may not ask this question of you.</p> <h3 id="duelists-block"><a aria-hidden="true" tabindex="-1" href="#duelists-block"><span class="icon icon-link"></span></a>Duelist’s Block</h3> <p>Replaces: Duelist’s Parry</p> <p>When you hack and slash, you take +2 armor forward.</p> <h3 id="con"><a aria-hidden="true" tabindex="-1" href="#con"><span class="icon icon-link"></span></a>Con</h3> <p>Replaces: Bamboozle</p> <p>When you <strong>parley with someone</strong>, on a 7+ you also take +1 forward with them
and get to ask their player one question which they must answer truthfully.</p> <h3 id="multiclass-master"><a aria-hidden="true" tabindex="-1" href="#multiclass-master"><span class="icon icon-link"></span></a>Multiclass Master</h3> <p>Get one move from another class. Treat your level as one lower for choosing
the move.</p>`,1);function d(e){var a=t();n(216),o(e,a)}export{d as default};
