import"./Bg9kRutz.js";import"./69_IOA4Y.js";import{n as a}from"./Dtm0V8su.js";import{a as o,t as i}from"./C-s_40rX.js";var n=i(`<h1 id="illithid-parasite"><a aria-hidden="true" tabindex="-1" href="#illithid-parasite"><span class="icon icon-link"></span></a>Illithid Parasite</h1> <p>The peoples of the Earth scramble around it, searching for meaning in their short lives. They shall not find it. They do not understand true joy is to commune with the Elder Brain; they cannot see.
You are not so weak. You are not so empty. You have left the womb, created by the Infinite Mind to seek out power and increase it’s strength. You will force them to see, partake in the joy as their last miserable act before they relenquish their meaningless lives to be reborn.
Reborn with power. Reborn with purpose, and meaning. Reborn as you truly are; illithid and finally, at long last, beautiful like nothing else can be.</p> <h2 id="stats"><a aria-hidden="true" tabindex="-1" href="#stats"><span class="icon icon-link"></span></a>Stats</h2> <p>Damage: d8
HP: 8+Constitution
Load: 8+STR</p> <h2 id="bonds"><a aria-hidden="true" tabindex="-1" href="#bonds"><span class="icon icon-link"></span></a>Bonds</h2> <p>Who have I tried to infect in the past?
Who here despises the illithid and what they stand for?
Who here has sought psychic power before?
Who here knows exactly what I am?
Who seeks here to gain illithid powers for their own?
Who is protecting me from the influence of the parasites, and how do you do it?</p> <h2 id="alignments"><a aria-hidden="true" tabindex="-1" href="#alignments"><span class="icon icon-link"></span></a>Alignments</h2> <p>Good: Keep others blissfully unaware of the Outer Chaos’ influence
Lawful: Use your psionic ability to interact with the Illithid
Neutral: Mask the true source of your power
Chaotic: Reject the impulses the parasite brings
Evil: Spread the power of the Elder Brain</p> <h2 id="backgrounds"><a aria-hidden="true" tabindex="-1" href="#backgrounds"><span class="icon icon-link"></span></a>Backgrounds</h2> <h3 id="servant-of-the-deep"><a aria-hidden="true" tabindex="-1" href="#servant-of-the-deep"><span class="icon icon-link"></span></a>Servant of the Deep</h3> <p>You are a parasite, burrowing deep within your hosts brain. No matter who they were, it is unimportant. You serve the Brain.
When you <strong>leave your hosts brain to devour another mind</strong>, you gain control of their body. You get hazy flashbacks from their mind; take +1 forward (once) to <em>Spout Lore</em> based on the knowledge from their memories.
If you are harmed outside of a host, you die.</p> <h3 id="cultist-of-the-mind"><a aria-hidden="true" tabindex="-1" href="#cultist-of-the-mind"><span class="icon icon-link"></span></a>Cultist of the Mind</h3> <p>You have long searched for this power, but after being granted it, you have found a way to control yourself and the parasite within, preventing it’s consumption of you.
When you meet another possessed of psychic ability, roll+INT. Choose 2/1:</p> <ul><li>Cut off their ability to access</li> <li>Give them a command they must follow</li></ul> <h3 id="infected-under-control"><a aria-hidden="true" tabindex="-1" href="#infected-under-control"><span class="icon icon-link"></span></a>Infected under Control</h3> <p>Before this horror began, you were another man. It threatens to consume you; you will not let it.
Choose one starting move from another class.</p> <h2 id="starting-moves"><a aria-hidden="true" tabindex="-1" href="#starting-moves"><span class="icon icon-link"></span></a>Starting Moves</h2> <p><em>A playbook by Magnus Anderson</em></p>`,1);function l(e){var t=n();a(34),o(e,t)}export{l as default};
