import"./Bg9kRutz.js";import"./69_IOA4Y.js";import{n as i}from"./BABQSOUd.js";import{a as n,t as o}from"./Z7e4vKxS.js";var t=o(`<h1 id="the-paladin"><a aria-hidden="true" tabindex="-1" href="#the-paladin"><span class="icon icon-link"></span></a>The Paladin</h1> <p>Hell awaits. An eternity of torment in fire or ice or whatever best suits the
sins of the damned throngs of Dungeon World. All that stands between the pits
of that grim torture and salvation is you. Holy man, armored war machine,
templar of the Good and the Light, right? The cleric may say his prayers at
night to the gods, dwelling in their heavens. The fighter may wield his sharp
sword in the name of “good” but you know. Only you.</p> <p>Eyes, hands, and sweet killing blow of the gods, you are. Yours is the gift of
righteousness and virtue. Of justice. Vision, too. A purity of intent that
your companions do not have.</p> <p>So guide these fools, paladin. Take up your holy cause and bring salvation to
the wastrel world.</p> <p>Vae victis, right?</p> <h2 id="names"><a aria-hidden="true" tabindex="-1" href="#names"><span class="icon icon-link"></span></a>Names</h2> <p>Thaddeus, Augustine, Lux, Cassius, Hadrian, Lucia, Octavia, Regulus, Valeria,
Sanguinus, Titanius</p> <h2 id="look"><a aria-hidden="true" tabindex="-1" href="#look"><span class="icon icon-link"></span></a>Look</h2> <p>Choose one for each:</p> <p>Kind Eyes, Fiery Eyes, or Glowing Eyes</p> <p>Helmet, Styled Hair, or Bald</p> <p>Worn Holy Symbol or Fancy Holy Symbol</p> <p>Fit Body, Bulky Body, or Thin Body</p> <h2 id="stats"><a aria-hidden="true" tabindex="-1" href="#stats"><span class="icon icon-link"></span></a>Stats</h2> <p>Your maximum HP is 10+Constitution.</p> <p>Your base damage is d10.</p> <h2 id="starting-moves"><a aria-hidden="true" tabindex="-1" href="#starting-moves"><span class="icon icon-link"></span></a>Starting Moves</h2> <p>You are human, so you get this move.</p> <h3 id="human"><a aria-hidden="true" tabindex="-1" href="#human"><span class="icon icon-link"></span></a>Human</h3> <p>When you <strong>pray for guidance, even for a moment, and ask, “What here is
evil?”</strong> the GM will tell you, honestly.</p> <p>You start with these moves:</p> <h3 id="lay-on-hands-cha"><a aria-hidden="true" tabindex="-1" href="#lay-on-hands-cha"><span class="icon icon-link"></span></a>Lay on Hands (Cha)</h3> <p>When you <strong>touch someone, skin to skin, and pray for their well-being</strong>,
roll+CHA. ✴On a 10+ you heal 1d8 damage or remove one disease. ✴On a 7–9, they
are healed, but the damage or disease is transferred to you.</p> <h3 id="armored"><a aria-hidden="true" tabindex="-1" href="#armored"><span class="icon icon-link"></span></a>Armored</h3> <p>You ignore the clumsy tag on armor you wear.</p> <h3 id="i-am-the-law"><a aria-hidden="true" tabindex="-1" href="#i-am-the-law"><span class="icon icon-link"></span></a>I Am the Law</h3> <p>When you <strong>give an NPC an order based on your divine authority</strong>, roll+Cha.
✴On a 7+, they choose one:</p> <ul><li>Do what you say</li> <li>Back away cautiously, then flee</li> <li>Attack you</li></ul> <p>✴On a 10+, you also take +1 forward against them. ✴On a miss, they do as they
please and you take -1 forward against them.</p> <h3 id="quest"><a aria-hidden="true" tabindex="-1" href="#quest"><span class="icon icon-link"></span></a>Quest</h3> <p>When you <strong>dedicate yourself to a mission through prayer and ritual
cleansing</strong>, state what you set out to do:</p> <ul><li>Slay _______, a great blight on the land</li> <li>Defend _______ from the iniquities that beset them</li> <li>Discover the truth of _______</li></ul> <p>Then choose up to two boons:</p> <ul><li>An unwavering sense of direction to _______.</li> <li>Invulnerability to _______ (e.g., edged weapons, fire, enchantment, etc.)</li> <li>A mark of divine authority</li> <li>Senses that pierce lies</li> <li>A voice that transcends language</li> <li>A freedom from hunger, thirst, and sleep</li></ul> <p>The GM will then tell you what vow or vows is required of you to maintain your
blessing:</p> <ul><li>Honor (forbidden: cowardly tactics and tricks)</li> <li>Temperance (forbidden: gluttony in food, drink, and pleasure of the flesh)</li> <li>Piety (required: observance of daily holy services)</li> <li>Valor (forbidden: suffering an evil creature to live)</li> <li>Truth (forbidden: lies)</li> <li>Hospitality (required: comfort to those in need, no matter who they are)</li></ul> <h2 id="alignment"><a aria-hidden="true" tabindex="-1" href="#alignment"><span class="icon icon-link"></span></a>Alignment</h2> <p>Choose an alignment:</p> <h3 id="lawful"><a aria-hidden="true" tabindex="-1" href="#lawful"><span class="icon icon-link"></span></a>Lawful</h3> <p>Deny mercy to a criminal or unbeliever.</p> <h3 id="good"><a aria-hidden="true" tabindex="-1" href="#good"><span class="icon icon-link"></span></a>Good</h3> <p>Endanger yourself to protect someone weaker than you.</p> <h2 id="gear"><a aria-hidden="true" tabindex="-1" href="#gear"><span class="icon icon-link"></span></a>Gear</h2> <p>Your load is 12+Str. You start with dungeon rations (5 uses, 1 weight),
scale armor (2 armor, 3 weight), and some mark of faith, describe it (0
weight). Choose your weapon:</p> <ul><li>Halberd (reach, +1 damage, two-handed, 2 weight)</li> <li>Long sword (close, +1 damage, 1 weight) and shield (+1 armor, 2 weight)</li></ul> <p>Choose one:</p> <ul><li>Adventuring gear (1 weight)</li> <li>Dungeon rations (1 weight) and healing potion (0 weight)</li></ul> <h2 id="bonds"><a aria-hidden="true" tabindex="-1" href="#bonds"><span class="icon icon-link"></span></a>Bonds</h2> <p>Fill in the name of one of your companions in at least one:</p> <p>_______________’s misguided behavior endangers their very
soul!</p> <p>_______________ has stood by me in battle and can be trusted
completely.</p> <p>I respect the beliefs of _______________ but hope they will
someday see the true way.</p> <p>_______________ is a brave soul, I have much to learn from
them.</p> <h2 id="advanced-moves"><a aria-hidden="true" tabindex="-1" href="#advanced-moves"><span class="icon icon-link"></span></a>Advanced Moves</h2> <p>When you gain a level from 2–5, choose from these moves.</p> <h3 id="divine-favor"><a aria-hidden="true" tabindex="-1" href="#divine-favor"><span class="icon icon-link"></span></a>Divine Favor</h3> <p>Dedicate yourself to a deity (name a new one or choose one that’s already
been established). You gain the commune and cast a spell cleric moves. When
you select this move, treat yourself as a cleric of level 1 for using spells.
Every time you gain a level thereafter, increase your effective cleric level
by 1.</p> <h3 id="bloody-aegis"><a aria-hidden="true" tabindex="-1" href="#bloody-aegis"><span class="icon icon-link"></span></a>Bloody Aegis</h3> <p>When you take damage you can grit your teeth and accept the blow. If you do
you take no damage but instead suffer a debility of your choice. If you
already have all six debilities you can’t use this move.</p> <h3 id="smite"><a aria-hidden="true" tabindex="-1" href="#smite"><span class="icon icon-link"></span></a>Smite</h3> <p>While on a quest you deal +1d4 damage.</p> <h3 id="exterminatus"><a aria-hidden="true" tabindex="-1" href="#exterminatus"><span class="icon icon-link"></span></a>Exterminatus</h3> <p>When you <strong>speak aloud your promise to defeat an enemy</strong>, you deal +2d4 damage
against that enemy and -4 damage against anyone else. This effect lasts until
the enemy is defeated. If you fail to defeat the enemy or give up the fight,
you can admit your failure, but the effect continues until you find a way to
redeem yourself.</p> <h3 id="charge"><a aria-hidden="true" tabindex="-1" href="#charge"><span class="icon icon-link"></span></a>Charge!</h3> <p>When you <strong>lead the charge into combat</strong>, those you lead take +1 forward.</p> <h3 id="staunch-defender"><a aria-hidden="true" tabindex="-1" href="#staunch-defender"><span class="icon icon-link"></span></a>Staunch Defender</h3> <p>When you defend you always get +1 hold, even on a 6-.</p> <h3 id="setup-strike"><a aria-hidden="true" tabindex="-1" href="#setup-strike"><span class="icon icon-link"></span></a>Setup Strike</h3> <p>When you hack and slash, choose an ally. Their next attack against your target
does +1d4 damage.</p> <h3 id="holy-protection"><a aria-hidden="true" tabindex="-1" href="#holy-protection"><span class="icon icon-link"></span></a>Holy Protection</h3> <p>You get +1 armor while on a quest.</p> <h3 id="voice-of-authority"><a aria-hidden="true" tabindex="-1" href="#voice-of-authority"><span class="icon icon-link"></span></a>Voice of Authority</h3> <p>Take +1 to order hirelings.</p> <h3 id="hospitaller"><a aria-hidden="true" tabindex="-1" href="#hospitaller"><span class="icon icon-link"></span></a>Hospitaller</h3> <p>When you heal an ally, you heal +1d8 damage.</p> <p>When you gain a level from 6–10, choose from these moves or the level 2–5
moves.</p> <h3 id="evidence-of-faith"><a aria-hidden="true" tabindex="-1" href="#evidence-of-faith"><span class="icon icon-link"></span></a>Evidence of Faith</h3> <p>Requires: Divine Favor</p> <p>When you <strong>see divine magic as it happens</strong>, you can ask the GM which deity
granted the spell and its effects. Take +1 when acting on the answers.</p> <h3 id="holy-smite"><a aria-hidden="true" tabindex="-1" href="#holy-smite"><span class="icon icon-link"></span></a>Holy Smite</h3> <p>Replaces: Smite</p> <p>While on a quest you deal +1d8 damage.</p> <h3 id="ever-onward"><a aria-hidden="true" tabindex="-1" href="#ever-onward"><span class="icon icon-link"></span></a>Ever Onward</h3> <p>Replaces: Charge!</p> <p>When you lead the charge into combat, those you lead take +1 forward and +2
armor forward.</p> <h3 id="impervious-defender"><a aria-hidden="true" tabindex="-1" href="#impervious-defender"><span class="icon icon-link"></span></a>Impervious Defender</h3> <p>Replaces: Staunch Defender</p> <p>When you defend you always get +1 hold, even on a 6-. When you get a 12+ to
defend instead of getting hold the nearest attacking creature is stymied
giving you a clear advantage, the GM will describe it.</p> <h3 id="tandem-strike"><a aria-hidden="true" tabindex="-1" href="#tandem-strike"><span class="icon icon-link"></span></a>Tandem Strike</h3> <p>Replaces: Setup Strike</p> <p>When you hack and slash, choose an ally. Their next attack against your target
does +1d4 damage and they take +1 forward against them.</p> <h3 id="divine-protection"><a aria-hidden="true" tabindex="-1" href="#divine-protection"><span class="icon icon-link"></span></a>Divine Protection</h3> <p>Replaces: Holy Protection</p> <p>You get +2 armor while on a quest.</p> <h3 id="divine-authority"><a aria-hidden="true" tabindex="-1" href="#divine-authority"><span class="icon icon-link"></span></a>Divine Authority</h3> <p>Replaces: Voice of Authority</p> <p>Take +1 to order hirelings. When you roll a 12+ the hireling transcends their
moment of fear and doubt and carries out your order with particular
effectiveness or efficiency.</p> <h3 id="perfect-hospitaller"><a aria-hidden="true" tabindex="-1" href="#perfect-hospitaller"><span class="icon icon-link"></span></a>Perfect Hospitaller</h3> <p>Replaces: Hospitaller</p> <p>When you heal an ally, you heal +2d8 damage.</p> <h3 id="indomitable"><a aria-hidden="true" tabindex="-1" href="#indomitable"><span class="icon icon-link"></span></a>Indomitable</h3> <p>When you suffer a debility (even through Bloody Aegis) take +1 forward
against whatever caused it.</p> <h3 id="perfect-knight"><a aria-hidden="true" tabindex="-1" href="#perfect-knight"><span class="icon icon-link"></span></a>Perfect Knight</h3> <p>When you quest you choose three boons instead of two.</p>`,1);function l(e){var a=t();i(206),n(e,a)}export{l as default};
