import"./Bg9kRutz.js";import"./69_IOA4Y.js";import{n as a}from"./Dtm0V8su.js";import{a as n,t}from"./C-s_40rX.js";var i=t(`<h1 id="trenchcoat"><a aria-hidden="true" tabindex="-1" href="#trenchcoat"><span class="icon icon-link"></span></a>Trenchcoat</h1> <p>Damage: d6
HP: 9+Constitution
Load: 5+STR</p> <h2 id="alignments"><a aria-hidden="true" tabindex="-1" href="#alignments"><span class="icon icon-link"></span></a>Alignments</h2> <p>Good: Defend those weaker than you
Neutral: Defeat a worthy opponent
Evil: Kill a defenseless or surrendered enemy</p> <h2 id="bonds"><a aria-hidden="true" tabindex="-1" href="#bonds"><span class="icon icon-link"></span></a>Bonds</h2> <p><em>suspects, but I’ve got a plan to fool them.</em> would lose their respect of me if they knew the truth. <em>thinks I’m a wise old owl who they’d best listen to.</em> is the only one we fully trust with our secret.
_ knew one of us, but doesn’t realize it’s me.</p> <h2 id="starting-moves"><a aria-hidden="true" tabindex="-1" href="#starting-moves"><span class="icon icon-link"></span></a>Starting Moves</h2> <h3 id="double-and-in-trouble"><a aria-hidden="true" tabindex="-1" href="#double-and-in-trouble"><span class="icon icon-link"></span></a>Double and in Trouble</h3> <p>When you <strong>both attack in a flurry of swordplay and magic (describe which element you use, or what effect you want)</strong>, roll +STR. Your wild magic causes trouble for everyone involved, and they may attack you back if they get a chance.</p> <ul><li>On a 10+, deal your damage +1d6-1</li> <li>On a 7+, deal your damage</li></ul> <h3 id="hear-me-out-on-this-one"><a aria-hidden="true" tabindex="-1" href="#hear-me-out-on-this-one"><span class="icon icon-link"></span></a>Hear me out on this one</h3> <p>When <strong>someone comes to you for advice and you tell them what you think is best</strong>, they take +1 forward to act on the answers, and you mark XP if the plan is crazy enough that they don’t. Lie about that last part when explaining this move to others.</p> <h3 id="my-eyes-are-up-here"><a aria-hidden="true" tabindex="-1" href="#my-eyes-are-up-here"><span class="icon icon-link"></span></a>My eyes are up here</h3> <p>When you talk to someone to distract them while your buddy gets to work within the trenchcoat, roll+CHA.
On a 10+, you’ve got just enough time to manage whatever plot you devised.
On a 7-9, choose one.</p> <ul><li>They realize you’re stalling for time</li> <li>You’ll need something else to make your plan work, the GM will tell you what</li></ul> <h3 id="accio-broom"><a aria-hidden="true" tabindex="-1" href="#accio-broom"><span class="icon icon-link"></span></a>Accio Broom</h3> <p>When you <strong>name an item and magically pull one into the trenchcoat</strong>, (hopefully the one you wanted, it was hard to tell from the description), roll+INT.
On a 10+, it flies straight into its many folds of fabric.
On a 7-9, choose one:</p> <ul><li>It clunks you on the head, I mean, belly.</li> <li>You’re not able to exert enough force to bring it to you.</li> <li>You have to stop moving and concentrate really hard, leaving you in a spot.</li></ul> <h3 id="hey-ive-got-one"><a aria-hidden="true" tabindex="-1" href="#hey-ive-got-one"><span class="icon icon-link"></span></a>Hey, I’ve Got One</h3> <p>When you <strong>produce something inconceivable from the folds of your trenchcoat</strong>, the specific details of when you got it or from what you conjured it will become clearer over time.</p> <h2 id="advanced-moves"><a aria-hidden="true" tabindex="-1" href="#advanced-moves"><span class="icon icon-link"></span></a>Advanced Moves</h2> <h3 id="spellcaster"><a aria-hidden="true" tabindex="-1" href="#spellcaster"><span class="icon icon-link"></span></a>Spellcaster</h3> <p>Gain the Wizard’s Cast a Spell and Prepare Spells moves. You can prepare half your level + 1 spells.</p> <h3 id="its-written-here-somewhere"><a aria-hidden="true" tabindex="-1" href="#its-written-here-somewhere"><span class="icon icon-link"></span></a>It’s written here somewhere!</h3> <p>When you <strong>forget what’s going on, get absorbed in remembering something, and wander around aimlessly</strong> (the GM will tell you how), take +1 to Spout Lore.</p> <h3 id="under-pressure"><a aria-hidden="true" tabindex="-1" href="#under-pressure"><span class="icon icon-link"></span></a>Under Pressure</h3> <p>When you <strong>roll 10+ on Double and in Trouble</strong>, you can choose to deal only your damage. If you do, the magic is actually pretty good, and mostly helpful to you rather than completely random.</p> <h3 id="unexpected-anatomy"><a aria-hidden="true" tabindex="-1" href="#unexpected-anatomy"><span class="icon icon-link"></span></a>Unexpected Anatomy</h3> <p>When you <strong>both do something conspicuous in order to avoid an attack</strong>, take the CHA debility. Reduce the damage to 0.</p> <h3 id="freakishly-tall"><a aria-hidden="true" tabindex="-1" href="#freakishly-tall"><span class="icon icon-link"></span></a>Freakishly tall</h3> <p>You’ve practiced looking menacing. When you draw yourself up to your full height, grow to about 4 feet, plus another 4 feet. Roll+CON: On a 10+, you look incredibly imposing. On a 7-9, you have to brace yourself against something, or else look foolish.</p> <p><em>A playbook by Magnus Anderson</em></p>`,1);function d(e){var o=i();a(62),n(e,o)}export{d as default};
