import"./Bg9kRutz.js";import"./69_IOA4Y.js";import{n as i}from"./lTSu4Se7.js";import{a as n,t as o}from"./i5qHrSzT.js";var r=o(`<h1 id="the-fighter"><a aria-hidden="true" tabindex="-1" href="#the-fighter"><span class="icon icon-link"></span></a>The Fighter</h1> <p>It’s a thankless job—living day to day by your armor and the skill of your
arm. To dive heedlessly into danger. They won’t be playing golden horns for
the time you took that knife to the ribs for them in the bar in Bucksberg. No
flock of angels to sing of the time you dragged them, still screaming, from
the edge of the Pits of Madness, no.</p> <p>Forget them.</p> <p>You do this for the guts and the glory. The scream of battle and the hot, hot
blood of it. You are a beast of iron. Your friends may carry blades of forged
steel but, fighter, you are steel. While your traveling companions might moan
about their wounds over a campfire in the wilderness, you bear your scars with
pride.</p> <p>You are the wall—let every danger smash itself to nothing on you. In the end,
you’ll be the last one standing.</p> <h2 id="names"><a aria-hidden="true" tabindex="-1" href="#names"><span class="icon icon-link"></span></a>Names</h2> <p><em>Dwarf</em>: Ozruk, Surtur, Brunhilda, Annika, Janos, Greta, Dim, Rundrig, Jarl,
Xotoq</p> <p><em>Elf</em>: Elohiir, Sharaseth, Hasrith, Shevaral, Cadeus, Eldar, Kithracet,
Thelian</p> <p><em>Halfling</em>: Finnegan, Olive, Randolph, Bartleby, Aubrey, Baldwin, Becca</p> <p><em>Human</em>: Hawke, Rudiger, Gregor, Brianne, Walton, Castor, Shanna, Ajax, Hob</p> <h2 id="look"><a aria-hidden="true" tabindex="-1" href="#look"><span class="icon icon-link"></span></a>Look</h2> <p>Choose one for each:</p> <p>Hard Eyes, Dead Eyes, or Eager Eyes</p> <p>Wild Hair, Shorn Hair, or Battered Helm</p> <p>Calloused Skin, Tanned Skin, or Scarred Skin</p> <p>Built Body, Lithe Body, or Ravaged Body</p> <h2 id="stats"><a aria-hidden="true" tabindex="-1" href="#stats"><span class="icon icon-link"></span></a>Stats</h2> <p>Your maximum HP is 10+Constitution.</p> <p>Your base damage is d10.</p> <h2 id="starting-moves"><a aria-hidden="true" tabindex="-1" href="#starting-moves"><span class="icon icon-link"></span></a>Starting Moves</h2> <p>Choose a race and gain the corresponding move:</p> <h3 id="dwarf"><a aria-hidden="true" tabindex="-1" href="#dwarf"><span class="icon icon-link"></span></a>Dwarf</h3> <p>When you <strong>share a drink with someone</strong>, you may parley with them using CON
instead of CHA.</p> <h3 id="elf"><a aria-hidden="true" tabindex="-1" href="#elf"><span class="icon icon-link"></span></a>Elf</h3> <p>Choose one weapon—you can always treat weapons of that type as if they had the
precise tag.</p> <h3 id="halfling"><a aria-hidden="true" tabindex="-1" href="#halfling"><span class="icon icon-link"></span></a>Halfling</h3> <p>When you defy danger and <strong>use your small size to your advantage</strong>, take +1.</p> <h3 id="human"><a aria-hidden="true" tabindex="-1" href="#human"><span class="icon icon-link"></span></a>Human</h3> <p>Once per battle you may reroll a single damage roll (yours or someone
else’s).</p> <p>You start with these moves:</p> <h3 id="bend-bars-lift-gates"><a aria-hidden="true" tabindex="-1" href="#bend-bars-lift-gates"><span class="icon icon-link"></span></a>Bend Bars, Lift Gates</h3> <p>When you <strong>use pure strength to destroy an inanimate obstacle</strong>, roll+Str. ✴On
a 10+, choose 3. ✴On a 7-9 choose 2.</p> <ul><li>It doesn’t take a very long time</li> <li>Nothing of value is damaged</li> <li>It doesn’t make an inordinate amount of noise</li> <li>You can fix the thing again without a lot of effort</li></ul> <h3 id="armored"><a aria-hidden="true" tabindex="-1" href="#armored"><span class="icon icon-link"></span></a>Armored</h3> <p>You ignore the clumsy tag on armor you wear.</p> <h3 id="signature-weapon"><a aria-hidden="true" tabindex="-1" href="#signature-weapon"><span class="icon icon-link"></span></a>Signature Weapon</h3> <p>This is your weapon. There are many like it, but this one is yours. Your
weapon is your best friend. It is your life. You master it as you master your
life. Your weapon, without you, is useless. Without your weapon, you are
useless. You must wield your weapon true.</p> <p>Choose a base description, all are 2 weight:</p> <ul><li>Sword</li> <li>Axe</li> <li>Hammer</li> <li>Spear</li> <li>Flail</li> <li>Fists</li></ul> <p>Choose the range that best fits your weapon:</p> <ul><li>Hand</li> <li>Close</li> <li>Reach</li></ul> <p>Choose two enhancements:</p> <ul><li>Hooks and spikes. +1 damage, but +1 weight.</li> <li>Sharp. +2 piercing.</li> <li>Perfectly weighted. Add precise.</li> <li>Serrated edges. +1 damage.</li> <li>Glows in the presence of one type of creature, your choice.</li> <li>Huge. Add messy and forceful.</li> <li>Versatile. Choose an additional range.</li> <li>Well-crafted. -1 weight.</li></ul> <p>Choose a look:</p> <ul><li>Ancient</li> <li>Unblemished</li> <li>Ornate</li> <li>Blood-stained</li> <li>Sinister</li></ul> <h2 id="alignment"><a aria-hidden="true" tabindex="-1" href="#alignment"><span class="icon icon-link"></span></a>Alignment</h2> <p>Choose an alignment:</p> <h3 id="good"><a aria-hidden="true" tabindex="-1" href="#good"><span class="icon icon-link"></span></a>Good</h3> <p>Defend those weaker than you.</p> <h3 id="neutral"><a aria-hidden="true" tabindex="-1" href="#neutral"><span class="icon icon-link"></span></a>Neutral</h3> <p>Defeat a worthy opponent.</p> <h3 id="evil"><a aria-hidden="true" tabindex="-1" href="#evil"><span class="icon icon-link"></span></a>Evil</h3> <p>Kill a defenseless or surrendered enemy.</p> <h2 id="gear"><a aria-hidden="true" tabindex="-1" href="#gear"><span class="icon icon-link"></span></a>Gear</h2> <p>Your load is 12+Str. You carry your signature weapon and dungeon rations (5
uses, 1 weight). Choose your defenses:</p> <ul><li>Chainmail (1 armor, 1 weight) and adventuring gear (1 weight)</li> <li>Scale armor (2 armor, 3 weight)</li></ul> <p>Choose two:</p> <ul><li>2 Healing potions (0 weight)</li> <li>Shield (+1 armor, 2 weight)</li> <li>Antitoxin (0 weight), dungeon rations (1 weight), and poultices and herbs (1 weight)</li> <li>22 coins</li></ul> <h2 id="bonds"><a aria-hidden="true" tabindex="-1" href="#bonds"><span class="icon icon-link"></span></a>Bonds</h2> <p>Fill in the name of one of your companions in at least one:</p> <p>_______________ owes me their life, whether they admit it or
not.</p> <p>I have sworn to protect _______________.</p> <p>I worry about the ability of _______________ to survive in the
dungeon.</p> <p>_______________ is soft, but I will make them hard like me.</p> <h2 id="advanced-moves"><a aria-hidden="true" tabindex="-1" href="#advanced-moves"><span class="icon icon-link"></span></a>Advanced Moves</h2> <p>When you gain a level from 2-5, choose from these moves.</p> <h3 id="merciless"><a aria-hidden="true" tabindex="-1" href="#merciless"><span class="icon icon-link"></span></a>Merciless</h3> <p>When you deal damage, deal +1d4 damage.</p> <h3 id="heirloom"><a aria-hidden="true" tabindex="-1" href="#heirloom"><span class="icon icon-link"></span></a>Heirloom</h3> <p>When you <strong>consult the spirits that reside within your signature weapon</strong>,
they will give you an insight relating to the current situation, and might ask
you some questions in return, roll+CHA. ✴On a 10+, the GM will give you good
detail. ✴On a 7-9, the GM will give you an impression.</p> <h3 id="armor-mastery"><a aria-hidden="true" tabindex="-1" href="#armor-mastery"><span class="icon icon-link"></span></a>Armor Mastery</h3> <p>When you <strong>make your armor take the brunt of damage dealt to you</strong>, the damage
is negated but you must reduce the armor value of your armor or shield (your
choice) by 1. The value is reduced each time you make this choice. If the
reduction leaves the item with 0 armor it is destroyed.</p> <h3 id="improved-weapon"><a aria-hidden="true" tabindex="-1" href="#improved-weapon"><span class="icon icon-link"></span></a>Improved Weapon</h3> <p>Choose one extra enhancement for your signature weapon.</p> <h3 id="seeing-red"><a aria-hidden="true" tabindex="-1" href="#seeing-red"><span class="icon icon-link"></span></a>Seeing Red</h3> <p>When you discern realities during combat, you take +1.</p> <h3 id="interrogator"><a aria-hidden="true" tabindex="-1" href="#interrogator"><span class="icon icon-link"></span></a>Interrogator</h3> <p>When you <strong>parley using threats of impending violence as leverage</strong>, you may
use STR instead of CHA.</p> <h3 id="scent-of-blood"><a aria-hidden="true" tabindex="-1" href="#scent-of-blood"><span class="icon icon-link"></span></a>Scent of Blood</h3> <p>When you hack and slash an enemy, your next attack against that same foe deals
+1d4 damage.</p> <h3 id="multiclass-dabbler"><a aria-hidden="true" tabindex="-1" href="#multiclass-dabbler"><span class="icon icon-link"></span></a>Multiclass Dabbler</h3> <p>Get one move from another class. Treat your level as one lower for choosing
the move.</p> <h3 id="iron-hide"><a aria-hidden="true" tabindex="-1" href="#iron-hide"><span class="icon icon-link"></span></a>Iron Hide</h3> <p>You gain +1 armor.</p> <h3 id="blacksmith"><a aria-hidden="true" tabindex="-1" href="#blacksmith"><span class="icon icon-link"></span></a>Blacksmith</h3> <p>When you have access to a forge you can graft the magical powers of a weapon
onto your signature weapon. This process destroys the magical weapon. Your
signature weapon gains the magical powers of the destroyed weapon.</p> <p>When you gain a level from 6-10, choose from these moves or the level 2-5
moves.</p> <h3 id="bloodthirsty"><a aria-hidden="true" tabindex="-1" href="#bloodthirsty"><span class="icon icon-link"></span></a>Bloodthirsty</h3> <p>Replaces: Merciless</p> <p>When you deal damage, deal +1d8 damage.</p> <h3 id="armored-perfection"><a aria-hidden="true" tabindex="-1" href="#armored-perfection"><span class="icon icon-link"></span></a>Armored Perfection</h3> <p>Replaces: Armor Mastery</p> <p>When you <strong>choose to let your armor take the brunt of damage dealt to you</strong>,
the damage is negated and you take +1 forward against the attacker, but you
must reduce the armor value of your armor or shield (your choice) by 1. The
value is reduced each time you make this choice. If the reduction leaves the
item with 0 armor it is destroyed.</p> <h3 id="evil-eye"><a aria-hidden="true" tabindex="-1" href="#evil-eye"><span class="icon icon-link"></span></a>Evil Eye</h3> <p>Requires: Seeing Red</p> <p>When you <strong>enter combat</strong>, roll+CHA. ✴On a 10+, hold 2. ✴On a 7-9, hold 1.
Spend your hold to make eye contact with an NPC present, who freezes or
flinches and can’t act until you break it off. ✴On a 6-, your enemies
immediately identify you as their biggest threat.</p> <h3 id="taste-of-blood"><a aria-hidden="true" tabindex="-1" href="#taste-of-blood"><span class="icon icon-link"></span></a>Taste of Blood</h3> <p>Replaces: Scent of Blood</p> <p>When you hack and slash an enemy, your next attack against that same foe deals
+1d8 damage.</p> <h3 id="multiclass-initiate"><a aria-hidden="true" tabindex="-1" href="#multiclass-initiate"><span class="icon icon-link"></span></a>Multiclass Initiate</h3> <p>Required: Multiclass Dabbler</p> <p>Get one move from another class. Treat your level as one lower for choosing
the move.</p> <h3 id="steel-hide"><a aria-hidden="true" tabindex="-1" href="#steel-hide"><span class="icon icon-link"></span></a>Steel Hide</h3> <p>Replaces: Iron Hide</p> <p>You gain +2 armor.</p> <h3 id="through-deaths-eyes"><a aria-hidden="true" tabindex="-1" href="#through-deaths-eyes"><span class="icon icon-link"></span></a>Through Death’s Eyes</h3> <p>When you <strong>go into battle</strong>, roll+WIS. ✴On a 10+, name someone who will live <strong>and</strong> someone who will die. ✴On a 7-9, name someone who will live <strong>or</strong> someone who will die. Name NPCs, not player characters. The GM will make your
vision come true, if it’s even remotely possible. ✴On a 6- you see your own
death and consequently take -1 ongoing throughout the battle.</p> <h3 id="eye-for-weaponry"><a aria-hidden="true" tabindex="-1" href="#eye-for-weaponry"><span class="icon icon-link"></span></a>Eye for Weaponry</h3> <p>When you look over an enemy’s weaponry, ask the GM how much damage they do.</p> <h3 id="superior-warrior"><a aria-hidden="true" tabindex="-1" href="#superior-warrior"><span class="icon icon-link"></span></a>Superior Warrior</h3> <p>When you hack and slash on a 12+ you deal your damage, avoid their attack, and
impress, dismay, or frighten your enemy.</p>`,1);function d(e){var a=r();i(220),n(e,a)}export{d as default};
