import"./Bg9kRutz.js";import"./69_IOA4Y.js";import{n}from"./BABQSOUd.js";import{a as i,t as o}from"./Z7e4vKxS.js";var t=o(`<h1 id="the-ranger"><a aria-hidden="true" tabindex="-1" href="#the-ranger"><span class="icon icon-link"></span></a>The Ranger</h1> <p>These city-born folk you travel with. Have they heard the call of the wolf?
Felt the winds howl in the bleak deserts of the East? Have they hunted their
prey with the bow and the knife like you? Hell no. That’s why they need you.</p> <p>Guide. Hunter. Creature of the wilds. You are these things and more. Your time
in the wilderness may have been solitary until now, but the call of some
greater thing—call it fate if you like—has cast your lot with these folk.
Brave, they may be. Powerful and strong, too. You know the secrets of the
spaces between, though.</p> <p>Without you, they’d be lost. Blaze a trail through the blood and dark,
strider.</p> <h2 id="names"><a aria-hidden="true" tabindex="-1" href="#names"><span class="icon icon-link"></span></a>Names</h2> <p><em>Elf</em>: Throndir, Elrosine, Aranwe, Celion, Dambrath, Lanethe</p> <p><em>Human</em>: Jonah, Halek, Brandon, Emory, Shrike, Nora, Diana</p> <h2 id="look"><a aria-hidden="true" tabindex="-1" href="#look"><span class="icon icon-link"></span></a>Look</h2> <p>Choose one for each:</p> <p>Wild Eyes, Sharp Eyes, or Animal Eyes</p> <p>Hooded Head, Wild Hair, or Bald</p> <p>Cape, Camouflage, or Traveling Clothes</p> <p>Lithe Body, Wild Body, or Sharp Body</p> <h2 id="stats"><a aria-hidden="true" tabindex="-1" href="#stats"><span class="icon icon-link"></span></a>Stats</h2> <p>Your maximum HP is 8+Constitution.</p> <p>Your base damage is d8.</p> <h2 id="starting-moves"><a aria-hidden="true" tabindex="-1" href="#starting-moves"><span class="icon icon-link"></span></a>Starting Moves</h2> <p>Choose a race and gain the corresponding move:</p> <h3 id="elf"><a aria-hidden="true" tabindex="-1" href="#elf"><span class="icon icon-link"></span></a>Elf</h3> <p>When you undertake a perilous journey through wilderness whatever job you take
you succeed as if you rolled a 10+.</p> <h3 id="human"><a aria-hidden="true" tabindex="-1" href="#human"><span class="icon icon-link"></span></a>Human</h3> <p>When you make camp in a dungeon or city, you don’t need to consume a ration.</p> <p>You start with these moves:</p> <h3 id="hunt-and-track-wis"><a aria-hidden="true" tabindex="-1" href="#hunt-and-track-wis"><span class="icon icon-link"></span></a>Hunt and Track (Wis)</h3> <p>When you <strong>follow a trail of clues left behind by passing creatures</strong>,
roll+WIS. ✴On a 7+, you follow the creature’s trail until there’s a
significant change in its direction or mode of travel. ✴On a 10+, you also
choose 1:</p> <ul><li>Gain a useful bit of information about your quarry, the GM will tell you what</li> <li>Determine what caused the trail to end</li></ul> <h3 id="called-shot"><a aria-hidden="true" tabindex="-1" href="#called-shot"><span class="icon icon-link"></span></a>Called Shot</h3> <p>When you <strong>attack a defenseless or surprised enemy at range</strong>, you can choose
to deal your damage or name your target and roll+DEX.</p> <ul><li>Head ✴10+: As 7–9, plus your damage ✴7-9: They do nothing but stand and drool for a few moments.</li> <li>Arms ✴10+: As 7-9, plus your damage ✴7-9: They drop anything they’re holding.</li> <li>Legs ✴10+: As 7-9, plus your damage ✴7-9: They’re hobbled and slow moving.</li></ul> <h3 id="animal-companion"><a aria-hidden="true" tabindex="-1" href="#animal-companion"><span class="icon icon-link"></span></a>Animal Companion</h3> <p>You have a supernatural connection with a loyal animal. You can’t talk to it
per se but it always acts as you wish it to. Name your animal companion and
choose a species:</p> <p>Wolf, cougar, bear, eagle, dog, hawk, cat, owl, pigeon, rat, mule</p> <p>Choose a base:</p> <ul><li>Ferocity +2, Cunning +1, 1 Armor, Instinct +1</li> <li>Ferocity +2, Cunning +2, 0 Armor, Instinct +1</li> <li>Ferocity +1, Cunning +2, 1 Armor, Instinct +1</li> <li>Ferocity +3, Cunning +1, 1 Armor, Instinct +2</li></ul> <p>Choose as many strengths as its ferocity:</p> <p>Fast, burly, huge, calm, adaptable, quick reflexes, tireless, camouflage,
ferocious, intimidating, keen senses, stealthy</p> <p>Your animal companion is trained to fight humanoids. Choose as many additional
trainings as its cunning:</p> <p>Hunt, search, scout, guard, fight monsters, perform, labor, travel</p> <p>Choose as many weaknesses as its instinct:</p> <p>Flighty, savage, slow, broken, frightening, forgetful, stubborn, lame</p> <h3 id="command"><a aria-hidden="true" tabindex="-1" href="#command"><span class="icon icon-link"></span></a>Command</h3> <p>When you work with your animal companion on something it’s trained in…</p> <ul><li>…and you attack the same target, add its ferocity to your damage</li> <li>…and you track, add its cunning to your roll</li> <li>…and you take damage, add its armor to your armor</li> <li>…and you discern realities, add its cunning to your roll</li> <li>…and you parley, add its cunning to your roll</li> <li>…and someone interferes with you, add its instinct to their roll</li></ul> <h2 id="alignment"><a aria-hidden="true" tabindex="-1" href="#alignment"><span class="icon icon-link"></span></a>Alignment</h2> <p>Choose an alignment:</p> <h3 id="chaotic"><a aria-hidden="true" tabindex="-1" href="#chaotic"><span class="icon icon-link"></span></a>Chaotic</h3> <p>Free someone from literal or figurative bonds.</p> <h3 id="good"><a aria-hidden="true" tabindex="-1" href="#good"><span class="icon icon-link"></span></a>Good</h3> <p>Endanger yourself to combat an unnatural threat.</p> <h3 id="neutral"><a aria-hidden="true" tabindex="-1" href="#neutral"><span class="icon icon-link"></span></a>Neutral</h3> <p>Help an animal or spirit of the wild.</p> <h2 id="gear"><a aria-hidden="true" tabindex="-1" href="#gear"><span class="icon icon-link"></span></a>Gear</h2> <p>Your load is 11+Str. You start with dungeon rations (5 uses, 1 weight),
leather armor (1 armor, 1 weight), and a bundle of arrows (3 ammo, 1
weight). Choose your armament:</p> <ul><li>Hunter’s bow (near, far, 1 weight) and short sword (close, 1 weight)</li> <li>Hunter’s bow (near, far, 1 weight) and spear (reach, 1 weight)</li></ul> <p>Choose one:</p> <ul><li>Adventuring gear (1 weight) and dungeon rations (1 weight)</li> <li>Adventuring gear (1 weight) and bundle of arrows (3 ammo, 1 weight)</li></ul> <h2 id="bonds"><a aria-hidden="true" tabindex="-1" href="#bonds"><span class="icon icon-link"></span></a>Bonds</h2> <p>Fill in the name of one of your companions in at least one:</p> <p>I have guided _______________ before and they owe me for it.</p> <p>_______________ is a friend of nature, so I will be their
friend as well.</p> <p>_______________ has no respect for nature, so I have no respect
for them.</p> <p>_______________ does not understand life in the wild, so I will
teach them.</p> <h2 id="advanced-moves"><a aria-hidden="true" tabindex="-1" href="#advanced-moves"><span class="icon icon-link"></span></a>Advanced Moves</h2> <p>You may take this move only if it is your first advancement.</p> <h3 id="half-elven"><a aria-hidden="true" tabindex="-1" href="#half-elven"><span class="icon icon-link"></span></a>Half-Elven</h3> <p>Somewhere in your lineage lies mixed blood and it begins to show its presence.
You gain the elf starting move if you took the human one at character creation
or vice versa.</p> <p>When you gain a level from 2-5, choose from these moves.</p> <h3 id="wild-empathy"><a aria-hidden="true" tabindex="-1" href="#wild-empathy"><span class="icon icon-link"></span></a>Wild Empathy</h3> <p>You can speak with and understand animals.</p> <h3 id="familiar-prey"><a aria-hidden="true" tabindex="-1" href="#familiar-prey"><span class="icon icon-link"></span></a>Familiar Prey</h3> <p>When you spout lore about a monster you use WIS instead of INT.</p> <h3 id="vipers-strike"><a aria-hidden="true" tabindex="-1" href="#vipers-strike"><span class="icon icon-link"></span></a>Viper’s Strike</h3> <p>When you strike an enemy with two weapons at once, add an extra 1d4 damage for
your off-hand strike.</p> <h3 id="camouflage"><a aria-hidden="true" tabindex="-1" href="#camouflage"><span class="icon icon-link"></span></a>Camouflage</h3> <p>When you <strong>keep still in natural surroundings</strong>, enemies never spot you until
you make a movement.</p> <h3 id="mans-best-friend"><a aria-hidden="true" tabindex="-1" href="#mans-best-friend"><span class="icon icon-link"></span></a>Man’s Best Friend</h3> <p>When you <strong>allow your animal companion to take a blow that was meant for
you</strong>, the damage is negated and your animal companion’s ferocity becomes 0.
If its ferocity is already 0 you can’t use this ability. When you have a few
hours of rest with your animal companion its ferocity returns to normal.</p> <h3 id="blot-out-the-sun"><a aria-hidden="true" tabindex="-1" href="#blot-out-the-sun"><span class="icon icon-link"></span></a>Blot Out the Sun</h3> <p>When you volley you may spend extra ammo before rolling. For each point of
ammo spent you may choose an extra target. Roll once and apply damage to all
targets.</p> <h3 id="well-trained"><a aria-hidden="true" tabindex="-1" href="#well-trained"><span class="icon icon-link"></span></a>Well-Trained</h3> <p>Choose another training for your animal companion.</p> <h3 id="god-amidst-the-wastes"><a aria-hidden="true" tabindex="-1" href="#god-amidst-the-wastes"><span class="icon icon-link"></span></a>God Amidst the Wastes</h3> <p>Dedicate yourself to a deity (name a new one or choose one that’s already
been established). You gain the commune and cast a spell cleric moves. When
you select this move, treat yourself as a cleric of level 1 for using spells.
Every time you gain a level thereafter, increase your effective cleric level
by 1.</p> <h3 id="follow-me"><a aria-hidden="true" tabindex="-1" href="#follow-me"><span class="icon icon-link"></span></a>Follow Me</h3> <p>When you undertake a perilous journey you can take two roles. You make a
separate roll for each.</p> <h3 id="a-safe-place"><a aria-hidden="true" tabindex="-1" href="#a-safe-place"><span class="icon icon-link"></span></a>A Safe Place</h3> <p>When you <strong>set the watch for the night</strong>, everyone takes +1 to take watch.</p> <p>When you gain a level from 6-10, choose from these moves or the level 2-5
moves.</p> <h3 id="wild-speech"><a aria-hidden="true" tabindex="-1" href="#wild-speech"><span class="icon icon-link"></span></a>Wild Speech</h3> <p>Replaces: Wild Empathy</p> <p>You can speak with and understand any non-magical, non-planar creature.</p> <h3 id="hunters-prey"><a aria-hidden="true" tabindex="-1" href="#hunters-prey"><span class="icon icon-link"></span></a>Hunter’s Prey</h3> <p>Replaces: Familiar Prey</p> <p>When you spout lore about a monster you use WIS instead of INT. On a 12+, in
addition to the normal effects, you get to ask the GM any one question about
the subject.</p> <h3 id="vipers-fangs"><a aria-hidden="true" tabindex="-1" href="#vipers-fangs"><span class="icon icon-link"></span></a>Viper’s Fangs</h3> <p>Replaces: Viper’s Strike</p> <p>When you strike an enemy with two weapons at once, add an extra 1d8 damage for
your off-hand strike.</p> <h3 id="smaugs-belly"><a aria-hidden="true" tabindex="-1" href="#smaugs-belly"><span class="icon icon-link"></span></a>Smaug’s Belly</h3> <p>When you know your target’s weakest point your arrows have 2 piercing.</p> <h3 id="strider"><a aria-hidden="true" tabindex="-1" href="#strider"><span class="icon icon-link"></span></a>Strider</h3> <p>Replaces: Follow Me</p> <p>When you undertake a perilous journey you can take two roles. Roll twice and
use the better result for both roles.</p> <h3 id="a-safer-place"><a aria-hidden="true" tabindex="-1" href="#a-safer-place"><span class="icon icon-link"></span></a>A Safer Place</h3> <p>Replaces: A Safe Place</p> <p>When you set the watch for the night everyone takes +1 to take watch. After a
night in camp when you set the watch everyone takes +1 forward.</p> <h3 id="observant"><a aria-hidden="true" tabindex="-1" href="#observant"><span class="icon icon-link"></span></a>Observant</h3> <p>When you hunt and track, on a hit you may also ask one question about the
creature you are tracking from the discern realities list for free.</p> <h3 id="special-trick"><a aria-hidden="true" tabindex="-1" href="#special-trick"><span class="icon icon-link"></span></a>Special Trick</h3> <p>Choose a move from another class. So long as you are working with your animal
companion you have access to that move.</p> <h3 id="unnatural-ally"><a aria-hidden="true" tabindex="-1" href="#unnatural-ally"><span class="icon icon-link"></span></a>Unnatural Ally</h3> <p>Your animal companion is a monster, not an animal. Describe it. Give it +2
ferocity and +1 instinct, plus a new training.</p>`,1);function d(a){var e=t();n(220),i(a,e)}export{d as default};
