import{o as e}from"./wYrreZjg.js";function t(e){let t=e.match(/^\((.+)\)$/);if(!t)return{count:1,names:[],hps:[]};let n=t[1].trim();if(n.endsWith(`,`)){let e=n.slice(0,-1).trim();if(e){let t=e.match(/^(-?\d+)hp\s+(.+)$/);return t?{count:1,names:[t[2]],hps:[+t[1]]}:{count:1,names:[e],hps:[]}}}if(/^\d+$/.test(n))return{count:+n,names:[],hps:[]};let r=n.split(`,`).map(e=>e.trim()).filter(Boolean),i=[],a=[],o=!1;for(let e of r){let t=e.match(/^(-?\d+)hp\s+(.+)$/);t?(a.push(+t[1]),i.push(t[2]),o=!0):(a.push(null),i.push(e))}return{count:i.length,names:i,hps:o?a:[]}}function n(t){return{...e(t),count:1,memberNames:[],custom:!0}}function r(e,r){if(!e.trim())return{matched:[],unmatched:``};let i=Math.max(...r.map(e=>e.name.split(/\s+/).length),1),a=new Map(r.map(e=>[e.name.toLowerCase(),e])),o=[],s=[],c=e.split(`
`),l=0;for(;l<c.length;){let e=c[l].trim();if(!e){l++;continue}if(e===`{`){l++;let e=[];for(;l<c.length&&!c[l].trim().startsWith(`}`);)e.push(c[l]),l++;let r=null;if(l<c.length){let e=c[l].trim().match(/^\}\s*(\(.*\))?\s*$/);e?.[1]&&(r=e[1]),l++}let i=n(e.join(`
`));if(r){let{count:e,names:n,hps:a}=t(r);i.count=e,i.memberNames=n,a.length&&(i.memberHps=a)}i.name!==`Unnamed`&&o.push(i);continue}let r=[],u=0,d=``;for(let t of e)t===`(`?u++:t===`)`&&(u=Math.max(0,u-1)),t===`,`&&u===0?(r.push(d.trim()),d=``):d+=t;d.trim()&&r.push(d.trim());for(let e of r){let n=e.match(/^(.+?)\s*(\([^)]*\))\s*$/),r=n?n[1].trim():e,c=n?n[2]:null,l=r.split(/\s+/).filter(Boolean),u=[];for(;l.length>0;){let e=!1;for(let n=Math.min(l.length,i);n>0;n--){let r=l.slice(0,n).join(` `).toLowerCase();if(a.has(r)){let{count:i,names:s,hps:u}=c?t(c):{count:1,names:[],hps:[]};o.push({...a.get(r),count:i,memberNames:s,...u.length?{memberHps:u}:{}}),l=l.slice(n),e=!0;break}}e||(u.push(l[0]),l=l.slice(1))}u.length&&s.push(u.join(` `))}l++}return{matched:o,unmatched:s.join(` `)}}function i(e,t,n){if(n?.some(e=>e!=null)){let r=e.map((e,t)=>n[t]==null?e:`${n[t]}hp ${e}`);return t===1?`(${r[0]},)`:`(${r.join(`, `)})`}return t===1&&e.length===1&&e[0]&&e[0]!==`#1`&&e[0]!==`HP`?`(${e[0]},)`:t>1?e.every((e,t)=>e===`#${t+1}`)?`(${t})`:`(${e.join(`, `)})`:``}function a(e,t,n,r,a){let o=e.split(`
`),s=t.toLowerCase();for(let e=0;e<o.length;e++)if(o[e].trim().replace(/\s*\(.*\)\s*$/,``).toLowerCase()===s){let t=o[e].trim().replace(/\s*\(.*\)\s*$/,``),s=i(n,r,a);return o[e]=s?`${t} ${s}`:t,o.join(`
`)}return e}function o(t){let n=[],r=t.split(`
`),i=0;for(;i<r.length;)if(r[i].trim()===`{`){i++;let t=[];for(;i<r.length&&!r[i].trim().startsWith(`}`);)t.push(r[i]),i++;i<r.length&&i++;let a=e(t.join(`
`));a.name&&a.name!==`Unnamed`&&n.push(a)}else i++;return n}function s(e){let t=[],n=e.split(`
`),r=0;for(;r<n.length;)if(/^```battle\s*$/i.test(n[r].trim())){r++;let e=[];for(;r<n.length&&!/^```/.test(n[r].trim());)e.push(n[r]),r++;r<n.length&&r++,t.push({text:e.join(`
`)})}else r++;return t}function c(e,t,n){let r=e.split(`
`),i=-1;for(let e=0;e<r.length;e++)if(/^```battle\s*$/i.test(r[e].trim())&&(i++,i===t)){let t=e+1;for(;t<r.length&&!/^```/.test(r[t].trim());)t++;let i=n.split(`
`);return r.splice(e+1,t-(e+1),...i),r.join(`
`)}return e}export{a,c as i,o as n,r,s as t};