export default [
	{
		name: 'Assassin Vine',
		tags: 'Solitary, Stealthy, Amorphous',
		hp: 15,
		armor: 1,
		attacks: [{ name: 'Thorns', damage: 'd10', tags: 'Close, Reach, Messy, 1 piercing' }],
		special: 'Plant',
		description:
			'Among the animals there exists a clear division ‘tween hunter and hunted. All it takes is a glance to know—by fangs and glowing eyes or claws or venomous sting—which of the creatures of this world are meant to kill and which stand to be killed. Such a split, if you have the eyes to see it, cuts the world of leaves and flowers in twain, as well. Druids in their forest circles know it. Rangers, too, might spot such a plant before it’s too late. Lay folk, though, they wander where they oughtn’t—paths into the deep woods covered in creeping vines and with a snap, these hungry ropes snap tight, dragging their meaty prey into the underbrush. Mind your feet, traveller.',
		instinct: 'To grow',
		moves: ['Shoot forth new growth', 'Attack the unwary'],
	},
	{
		name: 'Blink Dog',
		tags: 'Group, Small, Magical, Organized',
		hp: 6,
		armor: 4,
		attacks: [{ name: 'Bite', damage: 'd8', tags: 'Close' }],
		special: 'Illusion',
		description:
			'Now you see it, now you don’t. Hounds once owned by a sorcerer lord and imbued with a kind of illusory cloak, they escaped into the woods around his lair and began to breed with wolves and wild dogs of the forest. You can spot them, if you’re lucky, by the glittering silver of their coats and their strange, ululating howls. They have a remarkable talent for being not quite where they appear to be and use it to take down prey much stronger than themselves. If you find yourself facing a pack of blink dogs you might as well close your eyes and fight. You’ll have an easier time when not betrayed by your natural sight. By such sorceries are the natural places of the world polluted with unnatural things.',
		instinct: 'To hunt',
		moves: [
			'Give the appearance of being somewhere they’re not',
			'Summon the pack',
			'Move with amazing speed',
		],
	},
	{
		name: 'Centaur',
		tags: 'Horde, Large, Organized, Intelligent',
		hp: 11,
		armor: 1,
		attacks: [{ name: 'Bow', damage: 'd6+2', tags: 'Close, Reach, Near, 1 piercing' }],
		special: 'Half-horse, Half-man',
		description:
			'“It will be a gathering of clans unseen in this age. Call Stormhoof and Brightspear. Summon Whitemane and Ironflanks. Sound the horn and we shall begin our meeting—we shall speak the words and bind our people together. Too long have the men cut the ancient trees for their ships. The elves are weak and cowardly, friend to these mannish slime. It will be a cleansing fire from the darkest woods. Raise the red banner of war! Today we strike back against these apes and retake what is ours!”',
		instinct: 'To rage',
		moves: ['Overrun them', 'Fire a perfect bullseye', 'Move with unrelenting speed'],
	},
	{
		name: 'Chaos Ooze',
		tags: 'Solitary, Planar, Terrifying, Amorphous',
		hp: 23,
		armor: 1,
		attacks: [{ name: 'Warping touch', damage: 'd10', tags: 'Close, ignores armor' }],
		special: 'Ooze, Fragments of other planes embedded in it',
		description:
			'The barrier between Dungeon World and the elemental planes is not, as you might hope, a wall of stone. It’s much more porous. Places where the civil races do not often tread can sometimes, how to put this, spring a leak. Like a dam come just a little loose. Bits and pieces of the chaos spill out. Sometimes, they’ll congeal like an egg on a pan—that’s where we get the material for many of the Guild’s magical trinkets. Useful, right? Sometimes, though, it squirms and squishes around a bit and stays that way, warping all it touches into some other, strange form. Chaos begets chaos, and it grows.',
		instinct: 'To change',
		moves: ['Cause a change in appearance or substance', 'Briefly bridge the planes'],
	},
	{
		name: 'Cockatrice',
		tags: 'Group, Small, Hoarder',
		hp: 6,
		armor: 1,
		attacks: [{ name: 'Beak', damage: 'd8', tags: 'Close' }],
		special: 'Stone touch',
		description:
			'“I ain’t ever seen such a thing, sir. Rodrick thought it a chicken, maybe. Poor Rodrick. I figured it to be a lizard of a sort, though he was right—it had a beak and gray feathers like a chicken. Right, well, see, we found it in the woods, in a nest at the foot of a tree while we were out with the sow. Looking for mushrooms, sir. I told Rodrick we were—yes, sir, right sir, the bird—see, it was glaring at Rodrick and he tried to scare it off with a stick to steal the eggs but the thing pecked his hand. Quick it was, too. I tried to get him away but he just got slower and slower and…yes, as you see him now, sir. All frozen up like when we left the dog out overnight in winter two years back. Poor, stupid Rodrick. Weren’t no bird nor lizard, were it, sir?”',
		instinct: 'To defend the nest',
		moves: ['Start a slow transformation to stone'],
	},
	{
		name: 'Dryad',
		tags: 'Solitary, Magical, Intelligent, Devious',
		hp: 12,
		armor: 2,
		attacks: [{ name: 'Crushing vines', damage: '2d8 keep lowest 1', tags: 'Close' }],
		special: 'Plant',
		description:
			'More beautiful by far than any man or woman born in the civil realms. To gaze upon one is to fall in love. Deep and punishing, too. Thing is, they don’t love—not the fleshy folk who often find them, anyway. Their love is a primal thing, married to the woods—to a great oak that serves as home and mother and sacred place to them. It’s a curse to see one, too, they’ll never love you back. No matter what you do. No matter how you pledge yourself to them, they’ll always spurn you. If ever their oak comes to harm, you’ve not only the dryad’s wrath to contend with, but in every nearby village there’s a score of men with a secret longing in their heart, ready to murder you where you sleep for just a smile from such a creature.',
		instinct: 'To love nature passionately',
		moves: ['Entice a mortal', 'Merge into a tree', 'Turn nature against them'],
	},
	{
		name: 'Eagle Lord',
		tags: 'Group, Large, Organized, Intelligent',
		hp: 10,
		armor: 1,
		attacks: [
			{ name: 'Talons', damage: '2d8 keep highest 1 +1', tags: 'Close, Reach, 1 piercing' },
		],
		special: 'Mighty wings',
		description:
			'Some the size of horses. Bigger, even—the kings and queens of the eagles. Their cry pierces the mountain sky and woe to those who fall under the shadow of their mighty wings. The ancient wizards forged a pact with them in the primordial days. Men would take the plains and valleys and leave the mountaintops to the eagle lords. These sacred pacts should be honored, lest they set their talons into you. Lucky are the elves, for the makers of their treaties yet live and when danger comes to elvish lands, the eagle lords often serve as spies and mounts for them. Long-lived and proud, some might be willing to trade their ancient secrets for the right price, too.',
		instinct: 'To rule the heights',
		moves: ['Attack from the sky', 'Pull someone into the air', 'Call on ancient oaths'],
	},
	{
		name: 'Elvish Warrior',
		tags: 'Horde, Intelligent, Organized',
		hp: 3,
		armor: 2,
		attacks: [{ name: 'Sword', damage: '2d6 keep highest 1', tags: 'Close' }],
		special: 'Sharp sense',
		description:
			'”As with all things they undertake, the elves approach war as an art. I saw them fight, once. The Battle of Astrid’s Veil. Yes, I am that old, boy, now hush. A warrior-maiden, she was clad in plate that shone like the winter sky. White hair streaming and a pennant of ocean blue tied to her spear. She seemed to glide between the trees the way an angel might, striking out and bathing her blade in blood that steamed in the cold air. I never felt so small before. I trained with the master-at-arms of Battlemoore, you know. I’ve held a sword longer than you’ve been alive, boy, and in that one moment I knew that my skill meant nothing. Thank the gods the elves were with us then. A more beautiful and terrible thing I have never seen.”',
		instinct: 'To seek perfection',
		moves: ['Strike at a weak point', 'Set ancient plans in motion', 'Use the woods to advantage'],
	},
	{
		name: 'Elvish High Arcanist',
		tags: 'Solitary, Magical, Intelligent, Organized',
		hp: 12,
		armor: 0,
		attacks: [{ name: 'Arcane fire', damage: 'd10', tags: 'Near, Far, ignores armor' }],
		special: 'Sharp senses',
		description:
			'True elvish magic isn’t like the spells of men. Mannish wizardry is all rotes and formulas. They cheat to find the arcane secrets that resound all around them. They are deaf to the arcane symphony that sings in the woods. Elvish magic requires a fine ear to hear that symphony and the voice with which to sing. To harmonize with what is already resounding. Men bind the forces of magic to their will; Elves simply pluck the strings and hum along. The High Arcanists, in a way, have become more and less than any elf. The beat of their blood is the throbbing of all magic in this world.',
		instinct: 'To unleash power',
		moves: ['Work the magic that nature demands', 'Cast forth the elements'],
	},
	{
		name: 'Griffin',
		tags: 'Group, Large, Organized',
		hp: 10,
		armor: 1,
		attacks: [{ name: 'Talons', damage: 'd8+3', tags: 'Close, Reach, Forceful' }],
		special: 'Wings',
		description:
			'On first glance, one might mistake the griffin for another magical mistake like the manticore or the chimera. It looks the part, doesn’t it? These creatures have the regal haughtiness of a lion and the arrogant bearing of an eagle, but they temper those with the unshakeable loyalty of both. To earn the friendship of a griffin is to have an ally all your living days. Truly a gift, that. If you’re ever lucky enough to meet one be respectful and deferential above all else. It may not seem it but they can perceive the subtlest slights and will answer them with a sharp beak and talons.',
		instinct: 'To serve allies',
		moves: ['Judge someone’s worthiness', 'Carry an ally aloft', 'Strike from above'],
	},
	{
		name: 'Hill Giant',
		tags: 'Group, Huge, Intelligent, Organized',
		hp: 10,
		armor: 1,
		attacks: [{ name: 'Thrown rocks', damage: 'd8+3', tags: 'Reach, Near, Far, Forceful' }],
		description:
			'Ever seen an ogre before? Bigger than that. Dumber and meaner, too. Hope you like having cows thrown at you.',
		instinct: 'Ruin everything.',
		moves: ['Throw something', 'Do something stupid', 'Shake the earth'],
	},
	{
		name: 'Ogre',
		tags: 'Group, Large, Intelligent',
		hp: 10,
		armor: 1,
		attacks: [{ name: 'Club', damage: 'd8+5', tags: 'Close, Reach, Forceful' }],
		description:
			'A tale, then. Somewhere in the not-so-long history of the mannish race there was a divide. In days when men were merely dwellers-in-the-mud with no magic to call their own, they split in two: one camp left their caves and the dark forests and built the first city to honor the gods. The others, a wild and savage lot, retreated into darkness. They grew, there. In the deep woods a grim loathing for their softer kin gave them strength. They found dark gods of their own, there in the woods and hills. Ages passed and they bred tall and strong and full of hate. We have forged steel and they match it with their savagery. We may have forgotten our common roots, but somewhere, deep down, the ogres remember.',
		instinct: 'To return the world to darker days',
		moves: ['Destroy something', 'Fly into a rage', 'Take something by force'],
	},
	{
		name: 'Razor Boar',
		tags: 'Solitary',
		hp: 16,
		armor: 1,
		attacks: [{ name: 'Tusks', damage: 'd10', tags: 'Close, Messy, 3 piercing' }],
		description:
			'The tusks of the razor boar shred metal plate like so much tissue. Voracious, savage and unstoppable, they tower over their mundane kin. To kill one? A greater trophy of bravery and skill is hard to name, though I hear a razor boar killed the Drunkard King in a single thrust. You think you’re a better hunter than he?',
		instinct: 'To shred',
		moves: ['Rip them apart', 'Rend armor and weapons'],
	},
	{
		name: 'Satyr',
		tags: 'Group, Devious, Magical, Hoarder',
		hp: 10,
		armor: 1,
		attacks: [{ name: 'Charge', damage: '2d8 keep lowest 1', tags: 'Close' }],
		special: 'Enchantment',
		description:
			'One of only a very few creatures to be found in the old woods that don’t outright want to maim, kill, or eat us. They dwell in glades pierced by the sun, and dance on their funny goat-legs to enchanting music played on pipes made of bone and silver. They smile easily and, so long as you please them with jokes and sport, will treat our kind with friendliness. They’ve a mean streak, though, so if you cross them, make haste elsewhere; very few things hold a grudge like the stubborn satyr.',
		instinct: 'To enjoy',
		moves: [
			'Pull others into revelry through magic',
			'Force gifts upon them',
			'Play jokes with illusions and tricks',
		],
	},
	{
		name: 'Sprite',
		tags: 'Horde, Tiny, Stealthy, Magical, Devious, Intelligent',
		hp: 3,
		armor: 0,
		attacks: [{ name: 'Dagger', damage: '2d4 keep lowest 1', tags: 'Hand' }],
		special: 'Wings, Fey Magic',
		description: 'I’d classify them elementals, except that “being annoying” isn’t an element.',
		instinct: 'To play tricks',
		moves: [
			'Play a trick to expose someone’s true nature',
			'Confuse their senses',
			'Craft an illusion',
		],
	},
	{
		name: 'Treant',
		tags: 'Group, Huge, Intelligent, Amorphous',
		hp: 21,
		armor: 4,
		attacks: [{ name: 'Walloping branches', damage: 'd10+5', tags: 'Reach, Forceful' }],
		special: 'Wooden',
		description:
			'Old and tall and thick of bark walk amidst the tree-lined dark Strong and slow and forest-born, treants anger quick, we warn if to woods with axe ye go know the treants be thy foe',
		instinct: 'To protect nature',
		moves: ['Move with implacable strength', 'Set down roots', 'Spread old magic'],
	},
	{
		name: 'Werewolf',
		tags: 'Solitary, Intelligent',
		hp: 12,
		armor: 1,
		attacks: [{ name: 'Bite', damage: 'd10+2', tags: 'Close, Messy, 1 piercing' }],
		special: 'Weak to silver',
		description:
			'“Beautiful, isn’t it? The moon, I mean. She’s watching us, you know? Her pretty silver eyes watch us while we sleep. Mad, too—like all the most beautiful ones. If she were a woman, I’d bend my knee and make her my wife on the spot. No, I didn’t ask you here to speak about her, though. The chains? For your safety, not mine. I’m cursed, you see. You must have suspected. The sorcerer-kings called it “lycanthropy” in their day—passed on by a bite to make more of our kind. No, I could find no cure. Please, don’t be scared. You have the arrows I gave you? Silver, yes. Ah, you begin to understand. Don’t cry, sister. You must do this for me. I cannot bear more blood on my hands. You must end this. For me.”',
		instinct: 'To shed the appearance of civilization',
		moves: [
			'Transform to pass unnoticed as beast or man',
			'Strike from within',
			'Hunt like man and beast',
		],
	},
	{
		name: 'Worg',
		tags: 'Horde, Organized',
		hp: 3,
		armor: 1,
		attacks: [{ name: 'Bite', damage: 'd6', tags: 'Close' }],
		description:
			'As horses are to the civil races, so go the worg to the goblins. Mounts, fierce in battle, ridden by only the bravest and most dangerous, are found and bred in the forest primeval to serve the goblins in their wars on men. The only safe worg is a pup, separated from its mother. If you can find one of these, or make orphans of a litter with a sharp sword, you’ve got what could become a loyal protector or hunting hound in time. Train it well, mind you, for the worg are smart and never quite free of their primal urges.',
		instinct: 'To serve',
		moves: ['Carry a rider into battle', 'Give its rider an advantage'],
	},
];
