export default [
	{
		name: 'Living Tree',
		tags: 'Solitary, Huge, Intelligent',
		hp: 21,
		armor: 4,
		attacks: [{ name: 'Wooden Limbs', damage: 'd10+3', tags: 'Reach, Forceful, Messy', }],
		description: "So many people think they can just walk straight up to a tree and whack it with an axe. It's so common that this tree doesn't even take it personally, anymore. She just figures that if a few people die unjustly, well, a few trees are dying unjustly also.",
		instinct: 'To protect Nature',
		moves: ['Lash with entangling vines', 'Set down roots', 'Call upon the forest'],
	},
	{
		name: 'Pegasus',
		tags: 'Group, Construct',
		hp: 10,
		armor: 2,
		attacks: [{ name: 'Sharp Hooves', damage: 'd8+1', tags: 'Close, Forceful', }],
		special: 'Wings',
		description: "Lovely thing, isn't it? A fine white horse with the wings of a swan. Don't look like it ought to be able to fly, but it does. Hatching from little crystal eggs and bonded with their riders for life. There's still some beauty in the world, mark my words.",
		instinct: 'To carry aloft',
		moves: ['Land atop a foe', 'Fly like the wind', 'Protect their bonded'],
	},
	{
		name: 'Pegasi Knight',
		tags: 'Group, Construct',
		hp: 9,
		armor: 3,
		attacks: [{ name: 'Lance', damage: 'd8+1', tags: 'Messy, Reach', }],
		special: 'Mounted',
		description: 'Nature is a beautiful thing, and it must be protected. Who better to protect it, than by taming its greatest majesties? Bonded from birth, the Pegasi Knight and his steed fight as one.',
		instinct: 'To keep the natural order',
		moves: ['Leap from the air', 'Cast a druidic spell'],
	},
	{
		name: 'Gorilla-Bird',
		tags: 'Group, Wild',
		hp: 11,
		armor: 2,
		attacks: [{ name: 'Slamming Fists', damage: 'd12', tags: 'Messy', }],
		description: "Is it a bird? Is it a gorilla? Yes, and it is very, very used to being King of wherever it happens to be. Hope that you don't happen to be around also.",
		instinct: 'To dominate competition',
		moves: ['Drop a stone, then slam-dunk on top of it', 'Grab something and take flight', 'Search like a hawk'],
	},
];
