export default [
	{
		name: 'Formian Drone',
		tags: 'Horde, Organized, Cautious',
		hp: 7,
		armor: 4,
		attacks: [{ name: 'Bite', damage: 'd6', tags: 'Close' }],
		special: 'Hive connection, Insectoid',
		description:
			'With good cause, they say that these creatures (like all insects, really) are claimed by the powers of Law. They are order made flesh—a perfectly stratified society in which every larva, hatchling and adult knows its place in the great hive. The formian is some strange intersection of men and ants. (Though there are winged tribes that look like wasps out in the Western Desert, I’ve heard. And some with great sawtooth arms like mantids in the forests of the east.) Tall, with a hard shell and a harder mind, these particular formians are the bottom caste. They work the hills and honeycombs with single-minded joy that can be known only by such an alien mind.',
		instinct: 'To follow orders',
		moves: ['Raise the alarm', 'Create value for the hive', 'Assimilate'],
	},
	{
		name: 'Formian Taskmaster',
		tags: 'Group, Organized, Intelligent',
		hp: 6,
		armor: 3,
		attacks: [{ name: 'Spiked whip', damage: 'd8', tags: 'Close, Reach' }],
		special: 'Hive connection, Insectoid',
		description:
			'It takes two hands to rule an empire: one to wield the scepter and one to crack the whip. These ant-folk are that whip. Lucky for them, with two extra arms, that’s a lot of whip to crack. They oversee the vast swarms of worker drones that set to build the mighty caverns and ziggurats that dot the places that formians can be found. One in a hundred, these brutes stand two or three feet taller than their pale, near-mindless kin and have a sharper, crueler wit to match. They’ll often ignore the soft races (as we’re known) if we don’t interfere in a project, but get in the way of The Great Work and expect nothing less than their full attention. You don’t want their full attention.',
		instinct: 'To command',
		moves: ['Order drones into battle', 'Set great numbers in motion'],
	},
	{
		name: 'Formian Centurion',
		tags: 'Horde, Intelligent, Organized',
		hp: 7,
		armor: 3,
		attacks: [{ name: 'Barbed spear', damage: '2d6 keep highest 1 +2', tags: 'Close, Reach' }],
		special: 'Hive connection, Insectoid, Wings',
		description:
			'Whether in the form of a legionnaire, part of the formian standing army, or as a praetorian guard to the queen, every formian hive contains a great number of these most dangerous insectoids. Darker in carapace, often scarred with furrows and the ceremonial markings that set them apart from their drones, the formian centurions are their fighting force and rightly so. Born, bred and living for the singular purpose of killing the enemies of their hive, they fight with one mind and a hundred swords. Thus far, the powers of Law have seen fit to spare mankind a great war with these creatures, but we’ve seen them in skirmish—descending sometimes on border towns with their wings flickering in the heat or spilling up from a sandy mound to wipe clean a newly-dug mine. Theirs is an orderly bloodshed, committed with no pleasure but the completion of a goal.',
		instinct: 'To fight as ordered',
		moves: ['Advance as one', 'Summon reinforcements', 'Give a life for the hive'],
	},
	{
		name: 'Formian Queen',
		tags: 'Solitary, Huge, Organized, Intelligent, Hoarder',
		hp: 24,
		armor: 3,
		attacks: [{ name: 'Crushing mandibles', damage: 'd10+5', tags: 'Reach, Forceful' }],
		special: 'Hive connection, Insectoid',
		description:
			'At the heart of every hive, no matter its size or kind, lives a queen. As large as any giant, she sits protected by her guard, served by every drone and taskmaster with her own, singular purpose: to spread her kind and grow the hive. To birth the eggs. To nurture. We do not understand the minds of these creatures but it is known they can communicate with their children, somehow, over vast distances and that they begin to teach them the ways of earth and stone and war while still pale and wriggling larvae, without a word. To kill one is to set chaos on the hive; without their queen, the rest turn on one another in a mad, blind rage.',
		instinct: 'To spread formians',
		moves: [
			'Call every formian it spawned',
			'Release a half-formed larval mutation',
			'Organize and issue orders',
		],
	},
	{
		name: 'Gnoll Tracker',
		tags: 'Group, Organized, Intelligent',
		hp: 6,
		armor: 1,
		attacks: [{ name: 'Bow', damage: 'd8', tags: 'Near, Far' }],
		special: 'Scent-tracker',
		description:
			'Once they scent your blood, you can’t escape. Not without intervention from the gods, or the duke’s rangers at least. The desert scrub is a dangerous place to go exploring on your own and if you fall and break your leg or eat the wrong cactus, well, you’ll be lucky if you die of thirst before the gnolls find you. They prefer their prey alive, see—cracking bones and the screams of the dying lend a sort of succulence to a meal. Sickening creatures, no? They’ll hunt you, slow and steady, as you die. If you hear laughter in the desert wind, well, best pray Death comes to take you before they do.',
		instinct: 'To prey on weakness',
		moves: ['Doggedly track prey', 'Strike at a moment of weakness'],
	},
	{
		name: 'Gnoll Emissary',
		tags: 'Solitary, Divine, Intelligent, Organized',
		hp: 18,
		armor: 1,
		attacks: [{ name: 'Ceremonial dagger', damage: 'd10+2', tags: 'Close, Reach' }],
		special: 'Scent',
		description:
			'Oh, an emissary! How nice. I suspect you didn’t know the gnolls had ambassadors, did you? Yes, even these mangy hyenas have to make nice sometimes. No, no, not with us. Nor the dwarves, neither. No, the emissary is the one, among his packmates, who trucks directly with their dripping demon lord. Frightening? Too right. Every hound has a master with his hand on the chain. This gnoll hears his master’s voice. Hears it and obeys.',
		instinct: 'To share divine insight',
		moves: ['Pass on demonic influence', 'Drive the pack into a fervor'],
	},
	{
		name: 'Gnoll Alpha',
		tags: 'Solitary, Intelligent, Organized',
		hp: 12,
		armor: 2,
		attacks: [{ name: 'Sword', damage: '2d10 keep highest 1', tags: 'Close, 1 piercing' }],
		special: 'Scent',
		description:
			'Every pack has its top dog. Bigger, maybe—that’d be the simplest way. Often, though, with these lank and filthy mutts, it’s not about size or sharp teeth but about cruelty. About a willingness to kill your brothers and eat them while the pack watches. Willingness to desecrate the pack in a way that cows them to you. If they’re that awful to each other—to their living kin—think about how they must view us. It’s hard to be mere meat in a land of carnivores.',
		instinct: 'To drive the pack',
		moves: ['Demand obedience', 'Send the pack to hunt'],
	},
	{
		name: 'Orc Bloodwarrior',
		tags: 'Horde, Intelligent, Organized',
		hp: 3,
		armor: 0,
		attacks: [{ name: 'Jagged blade', damage: 'd6+2', tags: 'Close, Messy, 1 piercing' }],
		description:
			'The orcish horde is a savage, bloodthirsty, and hateful collection of tribes. There are myths and stories that tell of the origin of their rage—a demon curse, a homeland destroyed, elven magic gone wrong—but the truth has been lost to time. Every able orc, be it man or woman, child or elder, swears fealty to the warchief and their tribe and bears the jagged blade of a bloodwarrior. Men are trained to fight and kill—orcs are born to it.',
		instinct: 'To fight',
		moves: ['Fight with abandon', 'Revel in destruction'],
	},
	{
		name: 'Orc Berserker',
		tags: 'Solitary, Large, Divine, Intelligent, Organized',
		hp: 20,
		armor: 0,
		attacks: [{ name: 'Cleaver', damage: 'd10+5', tags: 'Close, Reach' }],
		special: 'Mutations',
		description:
			'Stained in the unholy ritual of Anointing By The Night’s Blood, some warriors of the horde rise to a kind of twisted knighthood. They trade their sanity for this honor, stepping halfway into a world of swirling madness. This makes berserkers the greatest of their tribe, though as time passes, the chaos spreads. The rare berserker that lives more than a few years becomes horrible and twisted, growing horns or an extra arm with which to grasp the iron cleavers they favor in battle.',
		instinct: 'To rage',
		moves: ['Fly into a frenzy', 'Unleash chaos'],
	},
	{
		name: 'Orc Breaker',
		tags: 'Solitary, Large',
		hp: 16,
		armor: 0,
		attacks: [{ name: 'Hammer', damage: 'd10+3', tags: 'Close, Reach, Forceful, ignores armor' }],
		description:
			'“Before you set out across the hordeland, brave sir, hark a moment to the tale of Sir Regnus. Regnus was like you, sir—a paladin of the Order, all a-shine in his plated armor and with a shield as tall as a man. Proud he was of it, too—Mirrorshield, he called himself. Tale goes that he’d set his eyes on rescuing some lost priest, a kidnap from the abbey on the borders. Regnus came across some orcs in his travels, a dozen or so, and thought, as one might, that they’d be no match. Battle was joined and all was well until one of them orcs emerged from the fray with a hammer bigger than any man ought to be able to wield. Built more like an ogre or a troll, they say it was, and with a single swing, it crushed Regnus to the ground, shield and all. It were no ordinary orc, they say. It were a breaker. They can’t make plate of their own, see, so maybe it’s jealousy drives these burly things to crush and shatter the way they do. Effective tactic, though. Careful out there.”',
		instinct: 'To smash',
		moves: ['Destroy armor or protection', 'Lay low the mighty'],
	},
	{
		name: 'Orc One-Eye',
		tags: 'Group, Divine, Magical, Intelligent, Organized',
		hp: 6,
		armor: 0,
		attacks: [
			{ name: 'Inflict Wounds', damage: 'd8+2', tags: 'Close, Reach, Near, Far, ignores armor' },
		],
		special: 'One eye',
		description:
			'In the name of He of Riven Sight and by the First Sacrifice of Elf-Flesh do we invoke the Old Powers. By the Second Sacrifice, I make my claim to what is mine—the dark magic of Night. In His image, I walk the path to Gor-sha-thak, the Iron Gallows! I call to the runes! I call to the clouded sky! Take this mortal organ, eat of the flesh of our enemy and give me what is mine!',
		instinct: 'To hate',
		moves: ['Rend flesh with divine magic', 'Take an eye', 'Make a sacrifice and grow in power'],
	},
	{
		name: 'Orc Shaman',
		tags: 'Solitary, Intelligent, Organized',
		hp: 12,
		armor: 0,
		attacks: [
			{ name: 'Elemental blast', damage: 'd10', tags: 'Close, Reach, Near, Far, ignores armor' },
		],
		special: 'Elemental power',
		description:
			'The orcs are as old a race as any. They cast bones in the dirt and called to the gods in the trees and stone as the elves built their first cities. They have waged wars, conquered kingdoms, and fallen into corruption in the aeons it took for men to crawl from their caves and dwarves to first see the light of the sun. Fitting, then, that the old ways still hold. They summon the powers of the world to work, to fight and to protect their people, as they have since the first nights.',
		instinct: 'To strengthen orc-kind',
		moves: [
			'Give protection of earth',
			'Give power of fire',
			'Give swiftness of water',
			'Give clarity of air',
		],
	},
	{
		name: 'Orc Slaver',
		tags: 'Horde, Stealthy, Intelligent, Organized',
		hp: 3,
		armor: 0,
		attacks: [{ name: 'Whip', damage: 'd6', tags: 'Close, Reach' }],
		description:
			'Red sails fly in the southern sea. Red sails and ships of bone, old wood and iron. The warfleet of the horde. Orcs down that way have taken to the sea, harassing island towns and stealing away with fishermen and their kin. It’s said the custom is spreading north and the orcs learn the value of free work. Taken to it like a sacred duty—especially if they can get their hands on elves. Hard to think of a grimmer fate than to live out your life on an orcish galley, back bent under the lash.',
		instinct: 'To take',
		moves: ['Take a captive', 'Pin someone under a net', 'Drug them'],
	},
	{
		name: 'Orc Shadowhunter',
		tags: 'Solitary, Stealthy, Magical, Intelligent',
		hp: 10,
		armor: 0,
		attacks: [{ name: 'Poisoned dagger', damage: 'd10', tags: 'Close, Reach, 1 piercing' }],
		special: 'Shadow cloak',
		description:
			'Not every attack by orcs is torches and screaming and enslavement. Among those who follow He of Riven Sight, poison and murder-in-the-dark are considered sacred arts. Enter the shadowhunter. Orcs cloaked in Night’s magic who slip into camps, towns and temples and end the lives of those within. Do not be so distracted by the howling of the berserkers that you don’t notice the knife at your back.',
		instinct: 'To kill in darkness',
		moves: ['Poison them', 'Melt into the shadows', 'Cloak them in darkness'],
	},
	{
		name: 'Orc Warchief',
		tags: 'Solitary, Intelligent, Organized',
		hp: 16,
		armor: 0,
		attacks: [
			{ name: 'Iron Sword of Ages', damage: '2d10 keep highest 1 +2', tags: 'Close, Reach' },
		],
		special: 'One-Eye blessings, Shaman blessings, Divine protection from mortal harm',
		description:
			'There are chiefs and there are leaders of the tribes among the orcs. There are those who rise to seize power and fall under the machinations of their foes. There is but one Warchief. One orc in all the horde who stands above the rest, bearing the blessings of the One-Eyes and the Shamans both. But one who walks with the elements under Night. But one who bears the Iron Sword of Ages and carries the ancient grudge against the civil races on his shoulders. The Warchief is to be respected, to be obeyed and above all else, to be feared. All glory to the Warchief.',
		instinct: 'To lead',
		moves: ['Start a war', 'Make a show of power', 'Enrage the tribes'],
	},
	{
		name: 'Triton Spy',
		tags: 'Solitary, Stealthy, Intelligent, Organized',
		hp: 12,
		armor: 2,
		attacks: [{ name: 'Trident', damage: '2d10 keep lowest 1', tags: 'Close, Near' }],
		special: 'Aquatic',
		description:
			'A fishing village caught one in their net, some time ago. Part a man and part some scaly sea creature, it spoke in a broken, spy-learned form of the common tongue before it suffocated in the open air. It told the fishermen of a coming tide, an inescapable swell of the power of some deep-sea god and that the triton empire would rise up and drag the land down into the ocean. The tale spread and now, when fishermen sail the choppy seas, they watch and worry that the dying triton’s tales were true. That there are powers deep below that watch and wait. They fear the tide is coming in.',
		instinct: 'To spy on the surface world',
		moves: ['Reveal their secrets', 'Strike at weakness'],
	},
	{
		name: 'Triton Tidecaller',
		tags: 'Group, Divine, Magical, Intelligent',
		hp: 6,
		armor: 2,
		attacks: [{ name: 'Waves', damage: 'd8+2', tags: 'Near, Far, ignores armor' }],
		special: 'Aquatic, Mutations',
		description:
			'Part priest, part outcast among their kind, the tidecaller speaks with the voice of the deeps. They can be known by their mutations—transparent skin, perhaps, or rows of teeth like a shark. Glowing eyes or fingertips, angler- lights in the darkness of their underwater kingdom. They speak in a strange tongue that can call and command creatures of the sea. They ride wild hippocampi and cast strange spells that rot through the wooden decks of ships or encrust them with barnacles heavy enough to sink. It is the tidecallers who come, now, back to the cities of the triton, bearing word that the prophecy is coming to pass. The world of men will drown in icy brine. The tidecallers speak and the lords begin to listen.',
		instinct: 'To bring on The Flood',
		moves: [
			'Cast a spell of water and destruction',
			'Command beasts of the sea',
			'Reveal divine proclamation',
		],
	},
	{
		name: 'Triton Sub-Mariner',
		tags: 'Group, Organized, Intelligent',
		hp: 6,
		armor: 3,
		attacks: [{ name: 'Harpoon', damage: '2d8 keep highest 1', tags: 'Close, Near, Far' }],
		special: 'Aquatic',
		description:
			'The triton are not a militant race by nature. They shy away from battle except when the sahuagin attack, and then they only defend themselves and retreat into the depths where their foes can’t follow. This trend begins to change. As the tidecallers come to rally their people, some triton men and women take up arms. They call these generals “sub-mariners” and build for them armor of shells and hardened glass. They swim in formation, wielding pikes and harpoons and attack the crews of ships that wander too far from port. Watch for their pennants of kelp on the horizon and the conch-cry of a call to battle and keep, if you can, your boats near shore.',
		instinct: 'To wage war',
		moves: ['Lead tritons to battle', 'Pull them beneath the waves'],
	},
	{
		name: 'Triton Noble',
		tags: 'Group, Organized, Intelligent',
		hp: 6,
		armor: 2,
		attacks: [{ name: 'Trident', damage: 'd8', tags: 'Close, Near, Far' }],
		special: 'Aquatic',
		description:
			'The triton ruling houses were chosen, they say, at the dawn of time. Granted lordship over all the races of the sea by some now-forgotten god. These bloodlines continue, passing rulership from father to daughter and mother to son through the ages. Each is allowed to rule their city in whatever way they choose—some alone or with their spouses, others in council of brothers and sisters. In ages past, they were known for their sagacity and bloodlines of even-temper were respected above all else. The tidecallers prophecy is changing that: nobles are expected to be strong, not wise. The nobles have begun to respond, and it is feared by some that the ancient blood is changing forever. It may be too late to turn back. Time and tide wait for none.',
		instinct: 'To lead',
		moves: ['Stir tritons to war', 'Call reinforcements'],
	},
];
