export default [
	{
		name: 'Abomination',
		tags: 'Solitary, Large, Construct, Terrifying',
		hp: 20,
		armor: 1,
		attacks: [{ name: 'Slam', damage: 'd10+3', tags: 'Close, Reach, Forceful' }],
		special: 'Many limbs, heads, and so on',
		description:
			'Corpses sewn onto corpses make up the bulk of these shambling masses of dark magic. Most undead are crafted to be controlled—made to serve some purpose like building a tower or serving as guardians. Not so the abomination. The last aspect of the ritual used to grant fire to their hellish limbs invokes a hatred so severe that the abomination knows but one task: to tear and rend at the very thing it cannot have—life. Many students of the black arts learn to their mortal dismay the most important fact about these hulks; an abomination knows no master.',
		instinct: 'To end life',
		moves: ['Tear flesh apart', 'Spill forth putrid guts'],
	},
	{
		name: 'Banshee',
		tags: 'Solitary, Magical, Intelligent',
		hp: 16,
		armor: 0,
		attacks: [{ name: 'Scream', damage: 'd10', tags: 'Near' }],
		special: 'Insubstantial',
		description:
			'Come away from an encounter with one of these vengeful spirits merely deaf and count yourself lucky for the rest of your peaceful, silent days. Often mistaken at first glance for a ghost or wandering spirit, the banshee reveals a far more deadly talent for sonic assault when angered. And her anger comes easy. A victim of betrayal (often by a loved one) the banshee makes known her displeasure with a roar or scream that can putrefy flesh and rend the senses. If you can help her get her vengeance, they say she might grant rewards. Whether the affection of a spurned spirit is a thing you’d want, well, that’s another question.',
		instinct: 'To get revenge',
		moves: [
			'Drown out all other sound with a ceaseless scream',
			'Unleash a skull-splitting noise',
			'Disappear into the mists',
		],
	},
	{
		name: 'Devourer',
		tags: 'Solitary, Large, Intelligent, Hoarder',
		hp: 16,
		armor: 1,
		attacks: [{ name: 'Smash', damage: 'd10+3', tags: 'Close, Reach, Forceful' }],
		description:
			'Most folk know that the undead feed on flesh. The warmth, blood and living tissue continue their unholy existence. This is true for most of the mindless dead, animated by black sorcery. Not so the devourer. When a particularly wicked person (often a manipulator of men, an apostate priest or the like) dies in a gruesome way, the dark powers of Dungeon World might bring them back to a kind of life. The devourer, however, does not feed on the flesh of men or elves. The devourer eats souls. It kills with a pleasure only the sentient can enjoy and in the moments of its victims’ expiry, draws breath like a drowning man and swallows a soul. What does it mean to have your soul eaten by such a creature? None dare ask for fear of finding out.',
		instinct: 'To feast on souls',
		moves: ['Devour or trap dying soul', 'Bargain for a soul’s return'],
	},
	{
		name: 'Dragonbone',
		tags: 'Solitary, Huge',
		hp: 20,
		armor: 2,
		attacks: [{ name: 'Bite', damage: 'd10+3', tags: 'Reach, Messy, 3 piercing' }],
		description:
			'Mystical sorcerers debate: is this creature truly undead or is it a golem made of a particularly rare and blasphemous material? The bones, sinews and scales of a dead dragon make up this bleak automaton. Winged but flightless, dragon- shaped but without the mighty fire of such a noble thing, the dragonbone serves its master with a twisted devotion and is often set to assault the keeps and towers of rival necromancers. It would take a being of some considerable evil to twist the remains of a dragon thus.',
		instinct: 'To serve',
		moves: ['Attack unrelentingly'],
	},
	{
		name: 'Draugr',
		tags: 'Horde, Organized',
		hp: 7,
		armor: 2,
		attacks: [{ name: 'Rusty sword', damage: 'd6+1', tags: 'Close, Reach' }],
		special: 'Icy touch',
		description:
			'In the Nordemark, the men and women tell tales in their wooden halls of a place where the noble dead go. A mead hall atop their heavenly mountain where men of valor go to await the final battle for the world. It is a goodly place. It is a place where one hopes to go after death. And the inglorious dead? Those who fall to poison or in an act of cowardice, warriors though they may be? Well, those mead halls aren’t open to all and sundry. Some come back, frozen and twisted and empowered by jealous rage and wage their eternal war not on the forces of giants or trolls but on the towns of the men they once knew.',
		instinct: 'To take from the living',
		moves: ['Freeze flesh', 'Call on the unworthy dead'],
	},
	{
		name: 'Ghost',
		tags: 'Solitary, Devious, Terrifying',
		hp: 16,
		armor: 0,
		attacks: [{ name: 'Phantom touch', damage: 'd6', tags: 'Close, Reach' }],
		special: 'Insubstantial',
		description:
			'Every culture tells the story the same way. You live, you love or you hate, you win or you lose, you die somehow you’re not too fond of and here you are, ghostly and full of disappointment and what have you. Some people take it upon themselves, brave and kindly folks, to seek out the dead and help them pass to their rightful rest. You can find them, most times, down at the tavern drinking away the terrors they’ve seen or babbling to themselves in the madhouse. Death takes a toll on the living, no matter how you come by it.',
		instinct: 'To haunt',
		moves: [
			'Reveal the terrifying nature of death',
			'Haunt a place of importance',
			'Offer information from the other side, at a price',
		],
	},
	{
		name: 'Ghoul',
		tags: 'Group',
		hp: 10,
		armor: 1,
		attacks: [{ name: 'Talons', damage: 'd8', tags: 'Close, Messy, 1 piercing' }],
		description:
			'Hunger. Hunger hunger hunger. Desperate clinging void-stomach-emptiness hunger. Sharp talons to rend flesh and teeth to tear and crack bones and suck out the soft marrow inside. Vomit up hate and screaming jealous anger and charge on twisted legs—scare the living flesh and sweeten it ever more with the stink of fear. Feast. Peasant or knight, wizard, sage, prince, or priest all make for such delicious meat.',
		instinct: 'To eat',
		moves: ['Gnaw off a body part', 'Gain the memories of their meal'],
	},
	{
		name: 'Lich',
		tags: 'Solitary, Magical, Intelligent, Cautious, Hoarder, Construct',
		hp: 16,
		armor: 5,
		attacks: [{ name: 'Magical Force', damage: 'd10+3', tags: 'Near, Far, ignores armor' }],
		description:
			'“At the end, they give you a scroll and a jeweled medallion to commemorate your achievements. Grand Master of Abjuration, I was called, then. Old man. Weak and wizened and just a bit too senile for them—those jealous halfwits. Barely apprentices, and they called themselves The New Council. It makes me sick, or would, if I still could be. They told me it was an honor and I would be remembered forever. It was like listening to my own eulogy. Fitting, in a way, don’t you think? It took me another ten years to learn the rituals and another four to collect the material and you see before you the fruits of my labor. I endure. I live. I will see the death of this age and the dawn of the next. It pains me to have to do this, but, you see, you cannot be permitted to endanger my research. When you meet Death, say hello for me, would you?”',
		instinct: 'To un-live',
		moves: [
			'Cast a perfected spell of death or destruction',
			'Set a ritual or great working into motion',
			'Reveal a preparation or plan already completed',
		],
	},
	{
		name: 'Mohrg',
		tags: 'Group',
		hp: 10,
		armor: 0,
		attacks: [{ name: 'Bite', damage: 'd8', tags: 'Close' }],
		description:
			'You never get away with murder. Not really. You might evade the law, might escape your own conscience in the end and die, fat and happy in a mansion somewhere. When the gods themselves notice your misdeeds, though, that’s where your luck runs out and a mohrg is born. The mohrg is a skeleton—flesh and skin and hair all rotted away. All but their guts—their twisted, knotted guts still spill from their bellies, magically preserved and often wrapped, noose-like, about their necks. They do not think, exactly, but they suffer. They kill and wreak havoc and their souls do not rest. Such is the punishment, both on them for the crime and on all mankind for daring to murder one another. The gods are just and they are harsh.',
		instinct: 'To wreak havoc',
		moves: ['Rage', 'Add to their collection of guts'],
	},
	{
		name: 'Mummy',
		tags: 'Solitary, Divine, Hoarder',
		hp: 16,
		armor: 1,
		attacks: [{ name: 'Smash', damage: 'd10+2', tags: 'Close' }],
		description:
			'There are cultures who revere the dead. They do not bury them in the cold earth and mourn their passing. These people spend weeks preparing the sacred corpse for its eternal rest. Temples, pyramids, and great vaults of stone are built to house them and are populated with slaves, pets and gold. The better to live in luxury beyond the Black Gates, no? Do not be tempted by these vaults—oh, I know that greedy look! Heed my warnings or risk a terrible fate, for the honored dead do not wish to be disturbed. Thievery will only raise their ire—don’t say I did not warn you!',
		instinct: 'To enjoy eternal rest',
		moves: ['Curse them', 'Wrap them up', 'Rise again'],
	},
	{
		name: 'Nightwing',
		tags: 'Horde, Stealthy',
		hp: 7,
		armor: 1,
		attacks: [{ name: 'Rend', damage: 'd6', tags: 'Close' }],
		special: 'Wings',
		description:
			'Scholars of the necromantic arts will tell you that the appellation “undead” applies not only to those who have lived, died, and been returned to a sort of partway living state. It is the proper name of any creature whose energy originates beyond the Black Gates. The creature men call the nightwing is one such—empowered by the negative light of Death’s domain. Taking the shape of massive, shadowy, winged creatures (some more bat-like, some like vultures, others like some ancient, leathery things) nightwings travel in predatory flocks, swooping down to strip the flesh from cattle, horses and unlucky peasants out past curfew. Watch the night sky for their red eyes. Listen for their screeching call. And hope to the gods you have something to hide under until they pass.',
		instinct: 'To hunt',
		moves: ['Attack from the night sky', 'Fly away with prey'],
	},
	{
		name: 'Shadow',
		tags: 'Horde, Large, Magical, Construct',
		hp: 11,
		armor: 4,
		attacks: [{ name: 'Shadow touch', damage: 'd6+1', tags: 'Close, Reach' }],
		special: 'Shadow Form',
		description:
			'We call to the elements. We call on fire, ever-burning. We summon water, life- giving. We beseech the earth, stable-standing. We cry to the air, forever- changing. These elements we recognize and give our thanks but ask to pass. The elemental we call upon this night knows another name. We call upon the element of Night. Shadow, we name you. Death’s messenger and black assassin, we claim for our own. Accept our sacrifice and do our bidding ’til the morning come.',
		instinct: 'To darken',
		moves: ['Snuff out light', 'Spawn another shadow from the dead'],
	},
	{
		name: 'Sigben',
		tags: 'Horde, Large, Construct',
		hp: 11,
		armor: 2,
		attacks: [{ name: 'Tail whip', damage: 'd6+1', tags: 'Close, Reach' }],
		special: 'Vampire spawn',
		description:
			'“Aswang-hound and hopping whip-tail! Sent by vampires on their two, twisted legs, these ugly things look like the head of a rat or a crocodile, maybe, furry though and sharp of tooth. They have withered wings, but cannot use them and long, whipping tails, spurred with poison tips. Stupid, vengeful and mischievous they cause all kinds of chaos when let out of the strange clay jars in which they’re born. Only a vampire could love such a wretched thing.”',
		instinct: 'To disturb',
		moves: ['Poison them', 'Do a vampire’s bidding'],
	},
	{
		name: 'Skeleton',
		tags: 'Horde',
		hp: 7,
		armor: 1,
		attacks: [{ name: 'Slam', damage: 'd6', tags: 'Close' }],
		description: 'Dem bones, dem bones, dem dry bones.',
		instinct: 'To take the semblance of life',
		moves: [
			'Act out what it did in life',
			'Snuff out the warmth of life',
			'Reconstruct from miscellaneous bones',
		],
	},
	{
		name: 'Spectre',
		tags: 'Solitary, Hoarder',
		hp: 12,
		armor: 0,
		attacks: [{ name: 'Withering touch', damage: 'd10', tags: 'Close' }],
		special: 'Insubstantial',
		description:
			'For some folk, when they pass, Death himself cannot release their grip on the places they love most. A priest whose devotion to the temple is greater than that of his god. A banking guild official who cannot bear to part with his vault. A drunk and his favorite tavern. All make excellent spectres. They act not out of the usual hunger that drives the undead, but jealousy. Jealousy that anyone else might come to love their home as much as they do and drive them out. These places belong to them and these invisible spirits will kill before they’ll let anyone send them to their rest.',
		instinct: 'To drive life from a place',
		moves: ['Turn their haunt against a creature', 'Bring the environment to life'],
	},
	{
		name: 'Vampire',
		tags: 'Group, Stealthy, Organized, Intelligent',
		hp: 10,
		armor: 2,
		attacks: [{ name: 'Supernatural force', damage: 'd8+5', tags: 'Close, Forceful, 1 piercing' }],
		special: 'Changing form, ancient mind',
		description:
			'We fear them, because they call to us. So much like us, or how we hope to be: beautiful, passionate, and powerful. They are drawn to us for what they cannot be: warm, kind, and alive. These tormented souls can only hope, at most, to pass their dreadful curse along. Every time they feed they run the risk of passing along their torture to another and in each one lives the twisted seed of its creator. Vampires beget vampires. Suffering begets suffering. Do not be drawn in by their seduction or you may be given their gift—a crown of shadows and the chains of eternal undying grief.',
		instinct: 'To manipulate',
		moves: ['Charm someone', 'Feed on their blood', 'Retreat to plan again'],
	},
	{
		name: 'Wight-Wolf',
		tags: 'Horde, Organized, Intelligent',
		hp: 7,
		armor: 1,
		attacks: [{ name: 'Pounce', damage: 'd6+1', tags: 'Close, 1 piercing' }],
		special: 'Shadow form',
		description:
			'Like the nightwing, the wight-wolf is a creature not spawned in our world. Somehow slipping the seals of the Black Gates of Death, these spirits take the shape of massive hounds or shadowy wolves and hunt the living for sport. They travel in packs, led by a mighty alpha, but bear a kind of intelligence unknown to true canines. Their wild hunts draw the attention of intelligent undead—liches, vampires and the like—who will sometimes make pacts with the alpha and serve a grim purpose together. Listen for the baying of the hounds of Death and pray that they do not howl for you.',
		instinct: 'To hunt',
		moves: ['Encircle prey', 'Summon the pack'],
	},
	{
		name: 'Zombie',
		tags: 'Horde',
		hp: 11,
		armor: 1,
		attacks: [{ name: 'Bite', damage: 'd6', tags: 'Close' }],
		description: 'When there’s no more room in Hell…',
		instinct: 'Braaaaaains',
		moves: [
			'Attack with overwhelming numbers',
			'Corner them',
			'Gain strength from the dead, spawn more zombies',
		],
	},
];
