import { monsterSections } from './monsters.js';

const A = '/games/dungeon-world/art';
export const pageArt = {
	// Playing
	introduction: { url: `${A}/introduction.png`, mirror: true },
	'character-creation': `${A}/character-creation.jpg`,
	'basic-moves': `${A}/basic-moves.jpg`,
	'playing-the-game': `${A}/playing-the-game.png`,
	'moves-discussion': `${A}/moves-discussion.png`,
	'example-of-play': `${A}/example-of-play.jpg`,
	equipment: { url: `${A}/equipment.jpg`, mirror: false },
	'magic-items': { url: `${A}/magic-items.jpg`, mirror: true },
	'first-session': `${A}/first-session.jpg`,
	'class-moves-discussion': `${A}/class-moves-discussion.png`,
	// Classes
	fighter: `${A}/fighter.webp`,
	wizard: `${A}/wizard.jpg`,
	cleric: `${A}/cleric.jpg`,
	thief: `${A}/thief.jpg`,
	paladin: `${A}/paladin.webp`,
	ranger: `${A}/ranger.jpg`,
	druid: `${A}/druid.webp`,
	barbarian: `${A}/barbarian.png`,
	bard: `${A}/bard.jpg`,
	branded: `${A}/branded.jpg`,
	'dashing-hero': `${A}/dashing-hero.jpg`,
	princess: `${A}/princess.jpg`,
	'arcane-duelist': `${A}/arcane-duelist.jpg`,
	dog: { url: `${A}/dog.jpg`, mirror: false },
	// Monster Zones
	'cavern-dwellers': `${A}/cavern-dwellers.jpeg`,
	'dark-woods': `${A}/dark-woods.jpeg`,
	'lower-depths': `${A}/lower-depths.jpg`,
	'twisted-experiments': `${A}/twisted-experiments.png`,
	'the-common-folk': `${A}/the-common-folk.jpg`,
	'ravenous-hordes': `${A}/ravenous-hordes.jpeg`,
	'planar-powers': `${A}/planar-powers.jpg`,
	'swamp-denizens': `${A}/swamp-denizens.jpg`,
	'undead-legions': `${A}/undead-legions.jpg`,
	'wild-beasts': `${A}/wild-beasts.jpg`,
	'godlike-beings': `${A}/godlike-beings.jpg`,
	'random-homebrew': { url: `${A}/random-homebrew.webp`, mirror: true },
	// GMing
	gm: `${A}/gm.png`,
	'the-world': `${A}/the-world.jpg`,
	fronts: `${A}/fronts.jpg`,
	'advanced-delving': `${A}/advanced-delving.jpg`,
	// Appendices
	conversion: `${A}/conversion.jpg`,
	npcs: `${A}/npcs.jpeg`,
	teaching: `${A}/teaching.jpg`,
	thanks: `${A}/thanks.jpg`,
	// Special pages
	'monsters-srd': `${A}/monsters-srd.jpg`,
	encounters: `${A}/encounters.webp`,
	'all-monsters': `${A}/all-monsters.jpg`,
	'user-monsters': `${A}/user-monsters.jpg`,
	// Spells
	'wizard-spells': `${A}/wizard-spells.webp`,
	'wizard-spells-srd': `${A}/wizard-spells.webp`,
	'cleric-miracles': `${A}/cleric-miracles.jpg`,
	'cleric-spells-srd': `${A}/cleric-spells-srd.png`,
	'druid-bindings': `${A}/druid-bindings.jpg`,
};

export const navigation = [
	{
		category: 'Playing',
		items: [
			{ title: 'Introduction', slug: 'introduction', source: 'srd', file: 'Introduction' },
			{
				title: 'Playing the Game',
				slug: 'playing-the-game',
				source: 'homebrew',
				file: 'Playing_the_Game',
				homebrew: true,
				srdSlug: 'playing-the-game-srd',
			},
			{
				title: 'Playing the Game',
				slug: 'playing-the-game-srd',
				source: 'srd',
				file: 'Playing_the_Game',
				hidden: true,
				homebrewSlug: 'playing-the-game',
			},
			{
				title: 'Character Creation',
				slug: 'character-creation',
				source: 'homebrew',
				file: 'Character_Creation',
				homebrew: true,
				srdSlug: 'character-creation-srd',
			},
			{
				title: 'Character Creation',
				slug: 'character-creation-srd',
				source: 'srd',
				file: 'Character_Creation',
				homebrewSlug: 'character-creation',
				hidden: true,
			},
			{
				title: 'Basic Moves',
				slug: 'basic-moves',
				source: 'homebrew',
				file: 'Basic_Moves',
				homebrew: true,
				srdSlug: 'basic-moves-srd',
			},
			{
				title: 'Basic Moves',
				slug: 'basic-moves-srd',
				source: 'srd',
				file: 'Moves',
				hidden: true,
				homebrewSlug: 'basic-moves',
			},
			{
				title: 'Equipment',
				slug: 'equipment',
				source: 'homebrew',
				file: 'Equipment',
				homebrew: true,
				srdSlug: 'equipment-srd',
			},
			{
				title: 'Equipment',
				slug: 'equipment-srd',
				source: 'srd',
				file: 'Equipment',
				hidden: true,
				homebrewSlug: 'equipment',
			},
			{
				title: 'Magic Items',
				slug: 'magic-items',
				source: 'homebrew',
				file: 'Magic_Items',
				homebrew: true,
				srdSlug: 'magic-items-srd',
			},
			{
				title: 'Magic Items',
				slug: 'magic-items-srd',
				source: 'srd',
				file: 'Magic_Items',
				hidden: true,
				homebrewSlug: 'magic-items',
			},
		],
	},
	{
		category: 'Characters',
		items: [
			{ title: 'Character Sheet', slug: 'character-sheet', skipSlug: true },
			{ title: 'Encounters', slug: 'encounters' },
			{ title: 'User Monsters', slug: 'user-monsters', skipSlug: true },
		],
	},
	{
		category: 'Classes',
		items: [
			{
				title: 'The Fighter',
				slug: 'fighter',
				source: 'homebrew',
				file: 'classes/Fighter',
				homebrew: true,
				srdSlug: 'fighter-srd',
			},
			{
				title: 'The Fighter',
				slug: 'fighter-srd',
				source: 'srd',
				file: 'Fighter',
				hidden: true,
				homebrewSlug: 'fighter',
			},
			{
				title: 'The Wizard',
				slug: 'wizard',
				source: 'homebrew',
				file: 'classes/Living_Magus',
				homebrew: true,
				srdSlug: 'wizard-srd',
			},
			{
				title: 'The Wizard',
				slug: 'wizard-srd',
				source: 'srd',
				file: 'Wizard',
				hidden: true,
				homebrewSlug: 'wizard',
			},
			{
				title: 'The Cleric',
				slug: 'cleric',
				source: 'homebrew',
				file: 'classes/Cleric',
				homebrew: true,
				srdSlug: 'cleric-srd',
			},
			{
				title: 'The Cleric',
				slug: 'cleric-srd',
				source: 'srd',
				file: 'Cleric',
				hidden: true,
				homebrewSlug: 'cleric',
			},
			{
				title: 'The Thief',
				slug: 'thief',
				source: 'homebrew',
				file: 'classes/Thief',
				homebrew: true,
				srdSlug: 'thief-srd',
			},
			{
				title: 'The Thief',
				slug: 'thief-srd',
				source: 'srd',
				file: 'Thief',
				hidden: true,
				homebrewSlug: 'thief',
			},
			{
				title: 'The Paladin',
				slug: 'paladin',
				source: 'homebrew',
				file: 'classes/Paladin',
				homebrew: true,
				srdSlug: 'paladin-srd',
			},
			{
				title: 'The Paladin',
				slug: 'paladin-srd',
				source: 'srd',
				file: 'Paladin',
				hidden: true,
				homebrewSlug: 'paladin',
			},
			{
				title: 'The Ranger',
				slug: 'ranger',
				source: 'homebrew',
				file: 'classes/Ranger',
				homebrew: true,
				srdSlug: 'ranger-srd',
			},
			{
				title: 'The Ranger',
				slug: 'ranger-srd',
				source: 'srd',
				file: 'Ranger',
				hidden: true,
				homebrewSlug: 'ranger',
			},
			{
				title: 'The Druid',
				slug: 'druid',
				source: 'homebrew',
				file: 'classes/Druidess',
				homebrew: true,
				srdSlug: 'druid-srd',
			},
			{
				title: 'The Druid',
				slug: 'druid-srd',
				source: 'srd',
				file: 'Druid',
				hidden: true,
				homebrewSlug: 'druid',
			},
			{
				title: 'The Barbarian',
				slug: 'barbarian',
				source: 'homebrew',
				file: 'classes/Barbarian',
				homebrew: true,
				srdSlug: 'barbarian-srd',
			},
			{
				title: 'The Barbarian',
				slug: 'barbarian-srd',
				source: 'srd',
				file: 'Barbarian',
				hidden: true,
				homebrewSlug: 'barbarian',
			},
			{
				title: 'The Bard',
				slug: 'bard',
				source: 'homebrew',
				file: 'classes/Bard',
				homebrew: true,
				srdSlug: 'bard-srd',
			},
			{
				title: 'The Bard',
				slug: 'bard-srd',
				source: 'srd',
				file: 'Bard',
				hidden: true,
				homebrewSlug: 'bard',
			},
			{
				title: 'The Alchemist',
				slug: 'alchemist',
				source: 'homebrew',
				file: 'classes/Alchemist',
				homebrew: true,
				hidden: true,
			},
			{
				title: 'The Illithid Parasite',
				slug: 'illithid-parasite',
				source: 'homebrew',
				file: 'classes/Illithid_Parasite',
				homebrew: true,
				hidden: true,
			},
			{
				title: 'The Trenchcoat',
				slug: 'trenchcoat',
				source: 'homebrew',
				file: 'classes/Trenchcoat',
				homebrew: true,
				hidden: true,
			},
			{
				title: 'The Branded',
				slug: 'branded',
				source: 'homebrew',
				file: 'classes/Branded',
				homebrew: true,
			},
			{
				title: 'The Dashing Hero',
				slug: 'dashing-hero',
				source: 'homebrew',
				file: 'classes/Dashing_Hero',
				homebrew: true,
			},
			{
				title: 'The Princess',
				slug: 'princess',
				source: 'homebrew',
				file: 'classes/Princess',
				homebrew: true,
			},
			{
				title: 'The Dog',
				slug: 'dog',
				source: 'homebrew',
				file: 'classes/Dog',
				homebrew: true,
			},

			{
				title: 'Arcane Duelist',
				slug: 'arcane-duelist',
				source: 'homebrew',
				file: 'classes/Arcane_Duelist',
				homebrew: true,
			},
		],
	},
	{
		category: 'Spells',
		items: [
			{
				title: 'Wizard Spells',
				slug: 'wizard-spells',
				source: 'homebrew',
				file: 'spells/Wizard_Spells',
				homebrew: true,
				srdSlug: 'wizard-spells-srd',
			},
			{
				title: 'Wizard Spells',
				slug: 'wizard-spells-srd',
				source: 'srd',
				file: 'Wizard_Spells',
				hidden: true,
				homebrewSlug: 'wizard-spells',
			},
			{
				title: 'Cleric Miracles',
				slug: 'cleric-miracles',
				source: 'homebrew',
				file: 'spells/Cleric_Miracles',
				homebrew: true,
				srdSlug: 'cleric-spells-srd',
			},
			{
				title: 'Cleric Spells',
				slug: 'cleric-spells-srd',
				source: 'srd',
				file: 'Cleric_Spells',
				hidden: true,
				homebrewSlug: 'cleric-miracles',
			},
			{
				title: 'Druid Bindings',
				slug: 'druid-bindings',
				source: 'homebrew',
				file: 'spells/Druid_Bindings',
				homebrew: true,
			},
		],
	},
	{
		category: 'Detailed Introduction',
		items: [
			{ title: 'Example of Play', slug: 'example-of-play', source: 'srd', file: 'Example' },
			{ title: 'First Session', slug: 'first-session', source: 'srd', file: 'First_Session' },
			{
				title: 'Moves Discussion',
				slug: 'moves-discussion',
				source: 'srd',
				file: 'Moves_Discussion',
			},
			{
				title: 'Class Moves Discussion',
				slug: 'class-moves-discussion',
				source: 'srd',
				file: 'Class_Moves_Discussion',
			},
		],
	},
	{
		category: 'GMing',
		items: [
			{ title: 'GM', slug: 'gm', source: 'srd', file: 'GM' },
			{ title: 'The World', slug: 'the-world', source: 'srd', file: 'The_World' },
			{ title: 'Fronts', slug: 'fronts', source: 'srd', file: 'Fronts' },
			{
				title: 'Advanced Delving',
				slug: 'advanced-delving',
				source: 'srd',
				file: 'Advanced_Delving',
			},
		],
	},
	{
		category: 'Monsters',
		items: [
			{ title: 'About Monsters', slug: 'monsters-srd', source: 'srd', file: 'Monsters' },
			{ title: 'All Monsters', slug: 'all-monsters', render: 'monsters' },
			...monsterSections.map((s) => ({
				title: s.name,
				slug: s.slug,
				render: 'monsters',
				monsterSection: s.slug,
				...(s.homebrew && { homebrew: true }),
			})),
		],
	},
	{
		category: 'Appendices',
		items: [
			{ title: 'Conversion', slug: 'conversion', source: 'srd', file: 'Conversion' },
			{ title: 'NPCs', slug: 'npcs', source: 'srd', file: 'NPCs' },
			{ title: 'Teaching the Game', slug: 'teaching', source: 'srd', file: 'Teaching' },
			{ title: 'Thanks', slug: 'thanks', source: 'srd', file: 'Thanks' },
		],
	},
];

export const contentIndex = {};
navigation.forEach((cat) => {
	cat.items.forEach((item) => {
		contentIndex[item.slug] = item;
	});
});

export const defaultSlug = 'introduction';
